### ISSUE TITLE
Error: Invalid forward slash character

### ISSUE THREAD

**Issue by tamlyn** [http-party/http-server#100]
I can start `http-server` OK but when I try to load any page in a browser I get a 400 response saying:

> Error: Invalid forward slash character

I've tracked down the error as coming from the [ecstatic](https://github.com/jesusabdullah/node-ecstatic) module but I don't know whether the issue is theirs or yours. 

I'm running node 0.10.26 on Windows 7.

**Comment by ravipksh** [comment]
For me fails (same error as above) on - 0.10.24
Works on - 0.10.29

**Comment by rakeshdebur** [comment]
I am facing the same issue. how do i revert http-server to an older version or is there any other way to fix it ?
