### ISSUE TITLE
ssl : default path is /root and not ./public

### ISSUE THREAD

**Issue by rcousture** [http-party/http-server#104]
When setting https mode; without specified path; the service renders the /root folder instead of the ./public folder.

Issue does not occur when starting the service in http (default is indeed ./public)

**Comment by Galaxy42** [comment]
I had the same problem. The solution is to run the command and after the "http-server" write a dot.
Then, if you need it you can run parameters.
It'll be like that:

> http-server .

Or if you want to write a port:
> http-server . -p 5856

**Comment by thornjad** [comment]
If this is still present in the latest version, this is definitely a bug! I'm going to close this for the long inactivity, but if anyone sees this again, please reopen!
