### ISSUE TITLE
add option to show referer

### ISSUE THREAD

**Issue by chovy** [http-party/http-server#121]

**Comment by thornjad** [comment]
I think this may be something better suited for the served website to do, rather than the server. If there is a referer being shared, it should be a header.

**Comment by thornjad** [comment]
I've changed my mind somewhat, it would be useful to have a verbose logging option which print out request and response headers. For that purpose, I'm currently looking at #493, #279 and #278

**Comment by thornjad** [comment]
I'm going to close this issue in favor of the more general #278, which would also solve this issue
