### ISSUE TITLE
Allow disabling sendfile so people using vagrant with shared folders are happy.

### ISSUE THREAD

**Issue by hak8or** [http-party/http-server#124]
I am developing an application and using http-server as a faster alternative from pythons micro http server (which also doesn't have the ability to disable sendfile usage) and noticed you guys don't have the ability to disable sendfile. Now, you may ask "Why would I want to do that?".

Well, I am doing my work in vagrant, which is surprisingly popular, and it allows sharing folders across the guest and host OS which is awesome. When it uses virtualbox, which is the default, we encounter [a bug](https://www.virtualbox.org/ticket/9069) that causes files to not sync up correctly across both OS's if the files in question are served by a webserver, which if you don't know about can be very difficult to track down. Of course virtualbox can fix this bug themselves which would mean you guys don't need to do anything, but sadly it seems to have gone unfixed for over three years now (even with a new [bug report](https://www.virtualbox.org/ticket/12597)), so that seems unlikely to happen anytime soon.

The [recommended fix](https://github.com/mitchellh/vagrant/issues/351#issuecomment-1339640) seems to be to disable sendfile in the server, which is possible in the larger ones such as Apache and Nginx, but understandably not in http-server since I assume you guys are going for a simple-is-good solution. Still, I was hoping that maybe you guys would consider exposing the option to users for disabling sendfile so us people with vagrant can use this for their projects while developing. For example, the gunicorn devs [decided](https://github.com/benoitc/gunicorn/issues/856) to go with an environment variable if you don't want to expose it via the CLI.

**Comment by indexzero** [comment]
A pull-request for this would be welcome :+1:

**Comment by thornjad** [comment]
This was a bug in VirtualBox which was fixed upstream
