### ISSUE TITLE
Serve multiple directories

### ISSUE THREAD

**Issue by yfr** [http-party/http-server#139]
Is it possible to serve multiple directories?

**Comment by marlic7** [comment]
+ it will be very useful possibility to configure simple aliases for eg.: /js => ./static/js

**Comment by Phlogi** [comment]
Is there already a way to just serve everything on a subdirectory?

**Comment by derhuerst** [comment]
@Phlogi what do you mean by that?

**Comment by Phlogi** [comment]
like this: domain.com/**myservice**/, i.e. adding a subfolder.

**Comment by derhuerst** [comment]
AFAIK, it's not possible with *http-server* out of the box.*ecstatic*, the core behind *http-server*, provides an [option `baseDir`](https://www.npmjs.com/package/ecstatic#opts-basedir).
