### ISSUE TITLE
--ssl to automatically generate in-memory certificates?

### ISSUE THREAD

**Issue by jokeyrhyme** [http-party/http-server#147]
`http-server` is one of my must-have tools, so thanks so much for sharing it. <3

I had one crazy, stupid question: is automatically making in-memory SSL certificates a completely horrible request?

This would make this a supremely-convenient tool, but I understand if it is out of scope or one of those security no-nos.

What do you think? Would you accept a pull request for this?

**Comment by thornjad** [comment]
I am of the opinion that this is out of scope for this project, but would be a very useful tool to be made. Something that wraps http-server and feeds it an auto-generated cert. 

There is also a little discussion of this in #562.
