### ISSUE TITLE
Support for CA bundles?

### ISSUE THREAD

**Issue by derhuerst** [http-party/http-server#155]
I have a certificate from Comodo for my domain as well as a CA bundle (several CA-related certificates). Some browsers require the CA Bundle to fully trust the website.

I'm looking for an option to pass a CA bundle to the underlying [`union` package](https://www.npmjs.com/package/union), since it [supports CA bundles](https://github.com/flatiron/union/blob/091b39a84f2f9a972ea1e15cf5922c99450c325d/README.md#createserveroptions). To make `http-server` support this, one would need to change [`bin/http-server`](https://github.com/indexzero/http-server/blob/master/bin/http-server).

**Comment by thornjad** [comment]
Despite this being supported by union, I'm unsure whether this is within the scope of a simple http server. Given the lack of activity in the last 6 years, I'm going to close this for now. Please re-open for further discussion if this is still a wanted feature.
