### ISSUE TITLE
--ext option not functional

### ISSUE THREAD

**Issue by premasagar** [http-party/http-server#160]
I find that when an html file is saved without a file extension, http-server serves it with `application/octet-stream`, even if I set `--ext html` in the cli options (anyway, `html` is the default).

Seen on Mac Yosemite; Node v2.0.2

**Comment by snuggles08** [comment]
+1

**Comment by Lacrymology** [comment]
+1

**Comment by wamoyo** [comment]
So this has been here since 2015? Hmm... wonder if it's a browser caching thing... I'll have a look on this.

**Comment by BigBlueHat** [comment]
A quick fix would simply be reordering this code and handling the `html` default extension by also setting `text/html` as the default media type:
https://github.com/indexzero/http-server/blob/fed98f2dbb87f1ea7a793e48a1975c20c9e970fa/lib/http-server.js#L50-L56

Anyone up for doing that? 😸
