### ISSUE TITLE
load large .js file,  request is not finished yet in  chrome browser

### ISSUE THREAD

**Issue by zlzdp** [http-party/http-server#226]

**Comment by dajbd** [comment]
http://127.0.0.1:8080/script/swiper/3.2.7/js/swiper.js   180kb
server:ecstatic-0.7.6

CAUTION: request is not finished yet!

**Comment by dajbd** [comment]
this CAUTION  makes  javascript not run in chrome

**Comment by dajbd** [comment]
when I minified swiper.js , this caution disappeared .

**Comment by dajbd** [comment]
minified swiper.js, also javascript running OK .

**Comment by thornjad** [comment]
Since there has been any more activity, I'm going to close this. If this is still an issue, there's a chance it may be fixed by #536
