### ISSUE TITLE
CLI -v parameter

### ISSUE THREAD

**Issue by roccomuso** [http-party/http-server#230]
Wouldn't be useful a -v flag to show the version number?

**Comment by ainthek** [comment]
+ 1 
--version PLEASE, it is useful for bug reporting

**Comment by derhuerst** [comment]
I guess you will have to submit a PR, that will hopefully get merged. There's almost no maintenance being done on this module.

**Comment by roccomuso** [comment]
I'll be happy to contribute, but there are still 38 PR pending and not enough mantainers...

**Comment by thornjad** [comment]
Added by #580
