### ISSUE TITLE
Open browser with URL

### ISSUE THREAD

**Issue by jamiewinder** [http-party/http-server#231]
The -o option is really handy, but unless I'm missing something I can't ask for anything other than the root to be opened? It'd be handy if we could specific a relative path, e.g.

`http-server -o /pages/index.html`

Opens browser with http://localhost:8080/pages/index.html

**Comment by SimplGy** [comment]
This would be handy for me. Looks like pretty isolated changes.

**Comment by lski** [comment]
I create a pull request #260 that allows for using both a relative path and still allow for using an absolute path in the same way as before. 

I think its a none breaking change as paths starting with a '/' didnt do anything anyway and will still allow anybodies pre-existing scripts to run :) plus its handy to be able to use an absolute url at times as well.

The only stipulation is the relative path must start with a forward slash '/'.

**Comment by craigmichaelmartin** [comment]
Related to issue #197. PR #250 addresses this directly, and #234, #260 add work arounds. If they could be reviewed, that would be great :)

**Comment by allenhwkim** [comment]
+1

**Comment by soyiatgit** [comment]
I am unbale to open my index.html page using any of following commannd

-o index
-o index.html
-o 'index.html'
-o '/index.html'

Am i misisng on something..I npm installed http-server today itself so believe to have the above change. The browser for me still opens at localhost:8080

**Comment by pmunin** [comment]
any updates on this issue?

**Comment by dominique-mueller** [comment]
Any news on this? Really seems like a useful feature to have!

**Comment by appurist** [comment]
I don't understand what the `path` part of  `-o [path]` was supposed to do it if did not behave this way.  At least _one_ of the four combinations above should be working. I find that (at least on my Linux installation) that it only launches the browser (at all) if I do not specify the path after `-o` at all.

**Comment by damianobarbati** [comment]
any news on this?=

**Comment by alistair-hmh** [comment]
Nothing opens for me at all.

**Comment by craigmichaelmartin** [comment]
There were a few PRs open to address this. It looks like https://github.com/indexzero/http-server/pull/250 was @thornjad chosen solution, and is waiting to be merged.

**Comment by thornjad** [comment]
#250 should be the one, I have a giant merge train in the works to get things moving.

**Comment by slavafomin** [comment]
I'm having the same problem. The `-o` option doesn't do anything on `Ubuntu 18.04.2 LTS`.

**Comment by LarryBattle** [comment]
This awesome project is lacking a pulse and this was the feature I needed the most.

## Workaround:

```
npm install live-server
live-server ./ --open='./example/'
```
Docs: https://www.npmjs.com/package/live-server

**Comment by thornjad** [comment]
This is working for me in version 0.12.3, please re-open if further problems are found
