### ISSUE TITLE
Header is send with illegal utf-8 characters

### ISSUE THREAD

**Issue by mpost** [http-party/http-server#255]
Using http-server on a system with a German local produces headers with illegal utf-8 characters that are not accepted by some clients:

`844424930447543-225-Fri Aug 28 2015 15:15:33 GMT+0200 (Mitteleurop�ische Sommerzeit)`

The `�` character is actually an `ä`.

**Comment by derhuerst** [comment]
Where is this being logged? How can I reproduce this?

**Comment by mpost** [comment]
Apparently this problem originated from a regression in the okhttp library. https://github.com/square/okhttp/issues/1998

Closing this for now.

**Comment by mpost** [comment]
The http header `If-None-Match` should not have utf-8 chars in its value according to the http spec (https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html). I therefore reopen this issue.

The problem is still remains in the okhttp as well but the http-server should not respond with it in the first place.

I have also opened an issue on okhttp and the check will be removed. https://github.com/square/okhttp/issues/2628

**Comment by donadley** [comment]
Is this issue resolved? 
I am also experiencing similar characters with French and Spanish. 
example: deuxi�me pr�nom

**Comment by rowi1de** [comment]
Can we make ` Headers.Builder addLenient` public please?
There may be some backends that support this, even if it's not RFC-Conform I have to communicate with these legacy services.

**Comment by thornjad** [comment]
@donadley @rowi1de are you still seeing this in the latest version of http-server? It's important that we get this investigated, but I want to be sure it isn't already fixed

**Comment by rowi1de** [comment]
@thornjad sorry, this is already 3 Years ago ... no clue

**Comment by thornjad** [comment]
No problem! Yeah I'm trying to clean up all these old issues. I'm going to close for now, anyone who sees this again with an up-to-date http-server, please re-open right away!
