### ISSUE TITLE
socket timeout

### ISSUE THREAD

**Issue by samlin99** [http-party/http-server#275]
sorry that I am new in here. I setup `http-server /foldername` and worked fine using default 8080 port. But it seems to timeout and close socket port 8080 after inactivity for x mins. Is it possible to have with no-timeout feature? Or how should I set up in correct way to have no timeout?

**Comment by julien-f** [comment]
FYI, the timeout is enforced even when there is activity on the socket.
[Node documentation](http://devdocs.io/node~4_lts/http#http_server_settimeout_msecs_callback).

And yes, it would be very nice to be able to disable timeouts as it breaks long transfers.

**Comment by tvStatic** [comment]
While we are waiting for the next release to support this, the workaround is to pass `--http-server-default-timeout=<timeout in ms>` as a parameter to node. You can disable the timeout altogether if timeout is 0.

Example that works for me:
```
node --http-server-default-timeout=0 ./node_modules/http-server/bin/http-server
```

See also: [http-server-default-timeout in node documentation](https://nodejs.org/api/cli.html#cli_http_server_default_timeout_milliseconds)
