### ISSUE TITLE
[Question] How to set cors headers?

### ISSUE THREAD

**Issue by gagan-bansal** [http-party/http-server#308]
I want to set cors header 
`Access-Control-Allow-Origin: *.mydomain.com`

How can it be set? 
Tried with --cors, but not able to set.
 `--cors='Access-Control-Allow-Origin: *.mydomain.com'`

**Comment by jeffbroadhurst18** [comment]
I am having the same issue. Please can you provide an example of how to use the --cors option. Thanks

**Comment by derhuerst** [comment]
With `--cors`:

```
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Range
```

With `--cors=Foo`:

```
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Range, Foo
```

It doesn't seem to work with `--cors foo`.

With `--cors=Foo,Bar`:

```
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Range, Foo, Bar
```

**Comment by bardiainjast** [comment]
@gagan-bansal @jeffbroadhurst18 use :
`http-server --cors='*' `

**Comment by dengue8830** [comment]
none of solutions worked for me :'v

`http-server --cors='*'`

`ttp-server --cors='http://localhost:3000/' .`

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3000/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

**Comment by dirkteucher** [comment]
None of these solutions seem to work when a child iframe is trying to access javascript objects in its parents container. Anyone have an idea why not?

**Comment by dirkteucher** [comment]
I found a hacky solution to work around this problem temporarily.

From CMD run the following: 
Linux 
**chromium-browser --disable-web-security --user-data-dir**
Windows
**chrome.exe --disable-web-security --user-data-dir**
Mac
**open -a Google\ Chrome --args --disable-web-security --user-data-dir**

This gets rid of ALL chromes security so use with caution. 

I would still like to know how to correctly allow iframe cors in http-server under the scenario I outlined in my last comment.

**Comment by michaelpalumbo** [comment]
Hi there, this is also presenting as an issue for me. I have tried each of the above-suggested cli flags to no avail. (I'm on osx sierra, fyi)

**Comment by imsontosh** [comment]
Hi, None of the solution works for me with Chrome :(

**Comment by SujayKrishnan** [comment]
Successfully working in Chrome; thanks all. I used Visual Studio Code (I have package npm http-server) and simply keyed in Terminal as follows: http-server --cors=*

**Comment by alicegherbison** [comment]
Hi there,
I am also having this issue. None of `http-server --cors=*`, `http-server --cors='*'` or `http-server --cors` (plus using hard refreshes) work in Chrome or Firefox to resolve it. Running OSX High Sierra.

**Comment by csakaszamok** [comment]
> Hi there,
> I am also having this issue. None of `http-server --cors=*`, `http-server --cors='*'` or `http-server --cors` (plus using hard refreshes) work in Chrome or Firefox to resolve it. Running OSX High Sierra.

same problem here
on osx does not not work the cors option

**Comment by PaTiToMaSteR** [comment]
that options against chrome don't work. confirmed, no matter the options :)

**Comment by peterjhart** [comment]
The only way that works for me (so far) is just `--cors`
http-server version: 0.12.1
node: 12.14.1
Chrome: 79.0.3945.130
macOS: 10.14.6 Mojave

Package script:
```
"serve": "http-server ./build -p 5625 --cors"
```

**Comment by zteater** [comment]
> Hi there,
> I am also having this issue. None of `http-server --cors=*`, `http-server --cors='*'` or `http-server --cors` (plus using hard refreshes) work in Chrome or Firefox to resolve it. Running OSX High Sierra.

`http-server --cors` worked for me after a hard refresh as you suggested.

**Comment by risingBirdSong** [comment]
none of the solutions were working for me with Chrome until,

"Note: Most browsers cache CORS policies for sometime in non-private mode. That’s why we need to open our browser in private mode. Otherwise, we keep getting the same CORS error we saw earlier even after refreshing the page"
https://elmprogramming.com/fetching-data-using-get.html

This fixed it for me!

**Comment by thornjad** [comment]
The original issue here appears to have been resolved, further discussion appears to be duplication of the issues in #394. Please re-open if this is not the case
