### ISSUE TITLE
Feature request: restrict requests from certain domain only

### ISSUE THREAD

**Issue by the1plummie** [http-party/http-server#312]
Can we support domain restriction? Say you have a domain `some.domain.com` that points to  your server at `1.2.3.4`, can you only allow requests that are in the form http://some.domain.com/some/endpoint and deny direct IP requests: http://1.2.3.4/some/endpoint?

**Comment by derhuerst** [comment]
It would at least be possible, based on the [`Host` HTTP header sent by the client](https://tools.ietf.org/html/rfc2616#section-14.23). But I don't think it belongs into this tiny module.

That may sound weird in the beginning, but there have been dozens of features requested, that each fulfill only a tiny user base's needs.

**Comment by thornjad** [comment]
I don't believe this fits into the scope of `http-server`. @BigBlueHat @indexzero what do you think?
