### ISSUE TITLE
throw new TypeError('The header content contains invalid characters') when proxy.  

### ISSUE THREAD

**Issue by ghost** [http-party/http-server#314]
I think is http-proxy@1.15.1  cause problems, Because I use http-proxy@1.8.0 work well. 

I use command _http-server -c-1 -P https://somurl.com_

**Comment by derhuerst** [comment]
Can you elaborate on where this error has been thrown (a stack trace if possible) and on your setup?

**Comment by ducklord** [comment]
Get the same error here. It is http-proxy@1.15.1 that is causing problems. It is because of the assumption of the interface does not fit what union has implemented, so the statusMessage is handled like a headers object. I posted a bug report to the http-proxy people, but there has been no response yet.
```_http_outgoing.js:351
      throw new TypeError('The header content contains invalid characters');
      ^

TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:351:13)
    at ResponseStream.writeHead (node_modules/union/lib/response-stream.js:75:21)
    at Array.writeStatusCode (node_modules/http-proxy/lib/http-proxy/passes/web-outgoing.js:113:11)
    at ClientRequest.<anonymous> (node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:157:20)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:433:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at Socket.socketOnData (_http_client.js:322:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

```

**Comment by derhuerst** [comment]
For reference purposes: https://github.com/nodejitsu/node-http-proxy/issues/1064

**Comment by reykjavikingur** [comment]
+1
I'm seeing this issue when I'm running my application with `http-proxy` 1.15.2, but the issue does not occur when I downgrade to 1.13.3.

I'm running Express with middleware am seeing extra (invalid) headers added for most of the proxied responses. Here is the raw response header list from my proxy server (for an arbitrary request):

```
HTTP/1.1 200 OK
0: O
1: K
X-Powered-By: Express
x-frame-options: SAMEORIGIN
last-modified: Mon, 17 Oct 2016 22:08:35 GMT
accept-ranges: bytes
cache-control: max-age=604800
expires: Tue, 25 Oct 2016 14:50:50 GMT
content-encoding: gzip
content-type: text/css
date: Sat, 22 Oct 2016 16:46:55 GMT
connection: close
vary: Accept-Encoding
Transfer-Encoding: chunked
```

For comparison, here is the response header list for the same request to the proxy target:

```
HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
Last-Modified: Mon, 17 Oct 2016 22:08:35 GMT
Accept-Ranges: bytes
Cache-Control: max-age=604800
Expires: Tue, 25 Oct 2016 14:50:50 GMT
Content-Encoding: gzip
Content-Type: text/css
Content-Length: 65265
Date: Sat, 22 Oct 2016 16:48:45 GMT
Connection: keep-alive
Vary: Accept-Encoding
```

The only unexpected headers from the proxy are `0: O` and `1: K`. In general, a response header is added for every character in the status description. For example, if the status is "304 Not Modified", then it adds the headers `0: N`, `1: o`, `2: t`, etc.

You can see my usage of `http-proxy` in the following file:
https://github.com/reykjavikingur/integration-proxy/blob/master/lib/integration-proxy.js

**Comment by jcrugzz** [comment]
This should be fixed with latest `union`. Do a fresh install after running `npm cache clean` of `http-server`

**Comment by thornjad** [comment]
Since this should be fixed, and there have been no more reports of errors, I'm going to close this. Please reopen if this still occurs on the latest version of http-server
