### ISSUE TITLE
Need a server that I can kill easily

### ISSUE THREAD

**Issue by GuyMograbi** [http-party/http-server#333]
Hi, 

I need an http server for tests.    
I also need to kill it after the tests finish.    

Is there any way to do this with http-server?     

Would be good if the process name was 'http-server' instead of node    
or if http-server could expose some URL that if called kills the process.

**Comment by derhuerst** [comment]
You can use `http-server` programmatically, see [`http-server.js`](https://github.com/indexzero/http-server/blob/b456b77/lib/http-server.js).

**Comment by GuyMograbi** [comment]
I want to write a bash script to run my tests. I prefer not to write more code for this.

**Comment by derhuerst** [comment]
Just saying that it would make sense to start a server from JS if your tests were in JS.

In a Bash script, you can kill `http-server` using e.g. `SIGTERM` like every other command line tool.

**Comment by GuyMograbi** [comment]
Some of my tests don't have JS code at all.. 
and to use SIGTERM I would have to remember the PID. 

I think running `http-server &` and then `killall http-server` is the simplest way to go. 
If this option existed I would definitely use it over anything else. 

It should be a really small change. 
something like `process.title = 'http-server'`

if I will open a PR for this, will you accept it?

**Comment by derhuerst** [comment]
> I think running http-server & and then killall http-server is the simplest way to go.

It is simple but certainly very dangerous. I often have multiple `http-server`s running on my local system and wouldn't expect a test of one specific lib to kill all of them. A PID file is really the cleaner solution here, and there's lots of tools for making that easier. Just search GitHub.

> It should be a really small change. something like `process.title = 'http-server'`
>
> if I will open a PR for this, will you accept it?

I'm not the maintainer of this module, just someone who helps out a lot in the issues. Unfortunately the maintainers of `http-server` seem to be pretty busy and almost never merge or give their opinion on issues.

*If I were* maintainer, I'd request you to use PID management tools like [`forever`](https://github.com/foreverjs/forever#readme) (or Shellscript-only solutions).

Still, setting `process.title` sounds like a reasonable thing in general.

**Comment by BigBlueHat** [comment]
@GuyMograbi feel free to open the `process.title` PR.

@derhuerst do you have an interest in hacking some `forever` stuff together?
