### ISSUE TITLE
Multiple paths, maybe some light URL re-writing?

### ISSUE THREAD

**Issue by brandonros** [http-party/http-server#348]

**Comment by BigBlueHat** [comment]
@brandonros anything specific you'd like here?

**Comment by SiXoS** [comment]
I have created a pull request for this. Hopefully it will be merged soon. You can find it here: https://github.com/SiXoS/http-server

**Comment by meszaros-lajos-gyorgy** [comment]
Duplicate: https://github.com/indexzero/http-server/issues/139

**Comment by sasmaster** [comment]
Very very important feature ( expose sub-dirs to  the wild). What's the status of it?

**Comment by BigBlueHat** [comment]
This is a larger project-direction discussion, really. The upstream `node-ecstatic` package doesn't support multiple directories (see https://github.com/jfhbrook/node-ecstatic/issues/192#issuecomment-301513115 for more).

Depending on your use case--which I'd love to hear more about--you may be best served (hehe) by using nginx (or similar). Something deliberately written for long running, large scale, multiple directory HTTP serving.

**Comment by xr0master** [comment]
It has issue with html5 routing.
For example: if I have the url "example.com/account" in my single application, then after refresh it will response 404. So I need a simple rule, if it is 404 (or file not found) then response the index.html

**Comment by thornjad** [comment]
Serving multiple directories is already covered in #139. Beyond that, I'm closing this as out of scope since http-server is a static server and doesn't officially support SPA's
