### ISSUE TITLE
Configure additional mime types

### ISSUE THREAD

**Issue by olegomon** [http-party/http-server#35]
add mime type support to enable streaming of video files with html 5 video tag

**Comment by dotnetCarpenter** [comment]
I'll give it shot. Just got an API implemented in the [upstream ecstatic](https://github.com/jfhbrook/node-ecstatic/pull/143/). If it gets accepted and I'm successful here... well, then it's done.

**Comment by dotnetCarpenter** [comment]
Can someone give me a hand with #152?
I can't figure out how to test the feature with vows. If I start http-server, I can request files with custom mime-types but no matter what I do in [http-server-test.js](https://github.com/indexzero/http-server/pull/152/files#diff-7a5fd917883091db4c5e5471a21bfb85R165), I get an ECONNREFUSED. I'm pretty sure it's a race condition but I can't figure out how to fix it.

Any ideas?

**Comment by timdp** [comment]
It'd also be nice if we could map `.mpd` to `application/dash+xml` for MPEG-DASH.

**Comment by stowball** [comment]
I would love to be able to serve SVGs correctly using the MIME type `images/svg+xml`

**Comment by BigBlueHat** [comment]
#152 just needs tests afaict. If anyone wants to right those, I'd be 👍 for merging that. Setting media types correctly is rather essential--and `ecstatic` already supports a way to set the mappings (between extension and media type) properly. So. Who's up for writing tests?! 😁

**Comment by 75lb** [comment]
MIME types [can be customised in local-web-server](https://github.com/lwsjs/local-web-server/wiki/How-to-customise-response-MIME-types), is that the kind of behaviour you're looking for?

**Comment by grokify** [comment]
+1 for SVG and/or customizable approach similar local-web-server.

**Comment by disfeng** [comment]
+1

**Comment by anderspitman** [comment]
Just want to chime in that lack of WebAssembly mime is forcing me to look for an alternative local server. http-server has beautifully handled all my needs up to this point and I'd hate to switch if I don't have to.

**Comment by paulmelnikow** [comment]
@anderspitman Did you find another option? At some point I switched from `http-server` to `serve`, but it has the same limitation.

**Comment by anderspitman** [comment]
@paulmelnikow I've been using https://crates.io/crates/https. That page includes installation instructions for non Rust developers as well.

**Comment by yiminghe** [comment]
https://crates.io/crates/https: http -m wasm:application/wasm

**Comment by ddennedy** [comment]
In case you landed here to figure out how to use the `--mimetypes` command line option and the syntax of its file, see here: https://github.com/jfhbrook/node-ecstatic#--mime-types-filename
(However, note that the option is not `--mime-types` in http-server!)

**Comment by acxz** [comment]
@ddennedy I'm afraid that didn't seem to change anything for me

**Comment by mtozlu** [comment]
Example mime type file can be found here;
https://github.com/http-party/http-server/blob/93fbb755fe55aa13878af9a91bc8e1a274522dbe/test/fixtures/custom_mime_type.types

**Comment by dsoudakov** [comment]
> In case you landed here to figure out how to use the `--mimetypes` command line option and the syntax of its file, see here: https://github.com/jfhbrook/node-ecstatic#--mime-types-filename (However, note that the option is not `--mime-types` in http-server!) For example,
> 
> ```
> $ cat hls/mime.types
> ecstatic({ mimeTypes: { 'application/vnd.apple.mpegurl': ['m3u8'] } })
> ```

Simply creating a custom.types file with "type ext1 ext2" works.

**Comment by insanity54** [comment]
I don't think this is mentioned in the docs, but the [source code](https://github.com/http-party/http-server/blob/8f7fcb08003952ec300874559690d0d75d241ffa/lib/core/index.js#L124) allows using stringified JSON to customize the mimetype. (no mime.types file required!) 

```bash
npx http-server -c-1 --mimetypes '{ "application/vnd.apple.mpegurl": ["mp4"] }'
```

**Comment by TexRx** [comment]
Heads up for anyone referencing @insanity54 example. In the example code, the `t` in `mimeTypes` should be capitalized. Otherwise, you get a CLI error.

Before (incorrect):
`npx http-server -c-1 --mimetypes '{ "application/vnd.apple.mpegurl": ["mp4"] }'`

After (correct):
`npx http-server -c-1 --mimeTypes '{ "application/vnd.apple.mpegurl": ["mp4"] }'`
