### ISSUE TITLE
Add `--find-port` parameter

### ISSUE THREAD

**Issue by BigBlueHat** [http-party/http-server#363]
#332 explored a `--find-port` parameter that was promising for situations when one wants to fallback from the default or defined port if it's unavailable...which will solve #325 & #215 bothersomeness.

**Comment by harttle** [comment]
989fa1c upgrades `portfinder`, which will solve #325 & #215. The new version of [`portfinder`][portfinder] will guarantee  the `port` found to be a free port.

In the current codebase, [`portfinder.basePort = 8080`][line84] sets the default port to `8080`, `portfinder` will find a free port (i.e. 8081, 8082, and so on.) if `8080` is not available.

[line84]: https://github.com/indexzero/http-server/blob/master/bin/http-server#L84
[portfinder]: https://github.com/indexzero/node-portfinder

**Comment by BigBlueHat** [comment]
So, the current `0.10.0` release does handle the fallback for the default port, but does not provide a fallback port--and still throws the error mentioned in #215 & #325.

Adding this `--find-port` option could fix that, but I'm not quite sure it's a good idea as specifying a port likely means the developer/operator expects that port to be available and if it is not, there *should* be an error...rather than just another port selected.

Open to input, though!

**Comment by ahmetb** [comment]
I think this should be implemented as `-p 0`  (port zero) flag . It's the unix convention for many server applications that is telling the OS to assign a random port. See #386.

**Comment by thornjad** [comment]
I'm inclined to agree with @ahmetb that `-p 0` seems the more "usual" way of specifying this. And, while http-server doesn't support _random_ port usage with `-p 0`, it should already work to walk upward from 8080 until it finds an open port. @BigBlueHat feel free to re-open this if you disagree, but I'm closing for now since `-p 0` already supports this functionality.

**Comment by thornjad** [comment]
This functionality is not currently documented, I'm adding that now.
