### ISSUE TITLE
The routing cannot be found on the refresh page

### ISSUE THREAD

**Issue by zhoulihan** [http-party/http-server#376]
Refresh the page will not find the routing, it is recommended to add a try_files, may be resolved

**Comment by BigBlueHat** [comment]
Thanks for reporting this issue. Did this happen when changing files in the directory? Were there any symlinks involved?

**Comment by yamishav** [comment]
+1

**Comment by xucito** [comment]
+1 - Occurs for me when I refresh a page that is not the root. Need to redirect to Index.html as it cannot find the path in the directory.

**Comment by ThunderRoid** [comment]
Same here, any fix yet or update on this?

**Comment by thornjad** [comment]
I'm not sure I understand what the issue is here. Are you getting a 404 error when refreshing pages?

**Comment by thornjad** [comment]
After some more searching, I believe this is a duplicate of #519
