### ISSUE TITLE
Add verbose flags

### ISSUE THREAD

**Issue by corysimmons** [http-party/http-server#401]
CLI aliases aren't explicit. Please add verbose flags?

**Comment by BigBlueHat** [comment]
There are only a few that don't have them, so I'd be happy to have them added if someone wants to whip up a PR for that.

**Comment by thornjad** [comment]
If I'm reading this correctly, this issue is about not documenting all available options in the help output and the README? Assuming that's correct, I'm going to close since I believe all options have a description now. Please reopen if I've misinterpreted!
