### ISSUE TITLE
Make https DX better

### ISSUE THREAD

**Issue by krzkaczor** [http-party/http-server#402]
Hey,
first of all great project! 

I would recommend one improvement. It would be nice if `http-server -S path` would generate automatically some dummy ssl certs for me so i don't need to do it by myself. `webpack-dev-server` does it and it's great. Otherwise I need to generate them with something like (this at least should be part of the readme):

`openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem`

Best!

**Comment by BigBlueHat** [comment]
I'm open to the auto-generation idea, but that's (obviously) trickier than a readme update, So 👍 to adding this to the readme for now--PR welcome. 😸

**Comment by therealshark** [comment]
[This fork](https://github.com/zombiecong/http-server/commit/c6ce761aad94f9d7ada0eac24ac708cbe57541c6) implements this feature. Looking at the codechanges this seems to be pretty staigt forward :)

**Comment by just-boris** [comment]
As an alternative example, webpack-dev-server, uses `selfsigned` module, as it is [shown here](https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/createCertificate.js) to generate local certificates.

**Comment by BigBlueHat** [comment]
#489 also brought this topic up. Would love some README updates from someone with time and attention to share.

Thanks!
🎩
