### ISSUE TITLE
Server not providing paths with . (example www.test.com/.well-know/ssl/data.txt)

### ISSUE THREAD

**Issue by tekbird** [http-party/http-server#441]
How to allow the server to resolve local path in which a directory name starts with dot.

**Comment by BigBlueHat** [comment]
`.` prefixed files and folders are typically hidden (by design) on filesystems, so whatever we used to enable them will need to take that into account.

**Comment by tekbird** [comment]
In linux, is there any way to do it?

**Comment by BigBlueHat** [comment]
First, we'd need tests for the `.well-known` scenario as well as tests against other likely-to-be-present` folders (or files) like `.git/` and `.gitignore`. Once we have those we can determine if it's http-server or [node-ecstatic](https://github.com/jfhbrook/node-ecstatic) that need the fix.

**Comment by thornjad** [comment]
This @tekbird would you please confirm if this issue is still present in the latest version of http-server? It looks like I'm able to serve dot-directories without an issue.

**Comment by thornjad** [comment]
Closing under the assumption this is now fixed, please reopen if this is not the case
