### ISSUE TITLE
Allow option to disable "Node.js v4.2.6/ ecstatic server running @ (ip address)"

### ISSUE THREAD

**Issue by TheSneakySniper** [http-party/http-server#442]
Can we add an option to disable this?

**Comment by BigBlueHat** [comment]
@TheSneakySniper more context would be helpful. Like, where are you seeing this, etc?

Thanks!

**Comment by TheSneakySniper** [comment]
@BigBlueHat I see this when I host a webpage using http-server. It's at the bottom of the hosted webpage.

**Comment by BigBlueHat** [comment]
@TheSneakySniper ah. You're seeing this on the directory listings that `node-ecstatic` is generating (which is where [that text](https://github.com/jfhbrook/node-ecstatic/blob/5038ff4169ad18507304a5579e0f2c3e50ec014f/lib/ecstatic/show-dir/index.js#L128-L132) is coming from also).

You can turn off those directory listings using `-d false` as a parameter.

Would that fix your issue? or are you wanting something beyond that (i.e. customize-able directory listings)?

**Comment by thornjad** [comment]
@TheSneakySniper can you confirm if using `-d false` solves your issue?
