### ISSUE TITLE
offline install http-server

### ISSUE THREAD

**Issue by muzi-8** [http-party/http-server#444]
hi：
I‘m confused with “how to offline install http-server”? Thanks!

**Comment by BigBlueHat** [comment]
@muzi-8 could you define "offline install"?

**Comment by guybi** [comment]
+1

**Comment by guybi** [comment]
offline - machine without access to the internet.

**Comment by BigBlueHat** [comment]
@guybi yeah...but to even get the repo one has to be...online. So, I'm trying to scope the request here.

If you've pulled down the repository (while online), you should be able to install it using local git references:
```sh
$ npm install -g path/to/http-server
```

It's a handy way to do development too.

Does that really need documenting by us, though? It's core to how `npm install` works:
https://docs.npmjs.com/cli/install

**Comment by thornjad** [comment]
Since this project is primarily distributed via `npm`, it has to come from the Internet at some point. We're happy to help get it installed in various ways, but offline is outside the scope of this project.
