### ISSUE TITLE
AutoReload on Save

### ISSUE THREAD

**Issue by myaseer** [http-party/http-server#446]
I just like this package very much. I use it like everyday. It is possible to include some feature like auto reload on the file changes, possible a feature update.

**Comment by cannap** [comment]
you can use nodemon for that watch the files and execute http-server again

**Comment by muellermarkus** [comment]
A working example would be:

```bash
 nodemon --exec "http-server ./"
```

**Comment by muellermarkus** [comment]
To run http-server with nodemon, this command works:

```bash
 nodemon --exec "http-server ./"
```

**Comment by roopkt** [comment]
Hi @muellermarkus 
`nodemon --exec "http-server -c-1 -p 8080"` this works for me as well. However it is keep opening new browser which is annoying any solution to reuse the active browser?

**Comment by muellermarkus** [comment]
@roopkt Sure that you did not accidentally add the `-o` flag ("*Open browser window after starting the server*") in `http-server`? Without this flag, no new browser windows should be opened.

**Comment by BigBlueHat** [comment]
Anyone fancy writing this `nodemon` usage up in the README?

**Comment by shilangyu** [comment]
I think the point of this issue was missed. By 'AutoReload' Im pretty sure OP means the browser reloading the page when files change, not 'Restarting' the server. OP please clarify

**Comment by thornjad** [comment]
If @shilangyu is correct, that's not something http-server is capable of doing, we can't control the browser like that without injecting JS, which is definitely out of scope.

**Comment by Joao-Pedro-S** [comment]
> I think the point of this issue was missed. By 'AutoReload' Im pretty sure OP means the browser reloading the page when files change, not 'Restarting' the server. OP please clarify

I think that the point is exactly the opposite: making the page change without need of reloading (Hot Reload)

**Comment by thornjad** [comment]
As far as I can tell, this feature request is not the responsibility of the server, since its the client that drives reloading (the server can't make the client reload). Please re-open if I misunderstand this

**Comment by rbrtmrtn** [comment]
@thornjad I can see where you're coming from, and may also gently disagree that it's up to the client to do live reloading. If my client is a web browser, how does the browser know when the local source files have changed? (I may also not be understanding something.)

As a point of comparison, here's lightweight, zero-config HTTP server that does live-reloading:

https://github.com/tapio/live-server

I'd love to use http-server as it looks like an awesome project and is more actively developed than live-server, but refreshing on every change would be tough to adapt to. Curious to hear if others have worked around this.
