### ISSUE TITLE
Multiple connections opened when serving simple HTML page?

### ISSUE THREAD

**Issue by rfrenz-avio** [http-party/http-server#449]
Hello,
I got a report from my network administrator of some odd traffic to/from a simple private site served using http-server.  He is seeing the server attempting to make outbound connections back to the client on higher ports (like 42000 and up).  Obviously I was concerned it was some kind of hack, but I see it too, even on a completely isolated local test, e.g.

1. Create an empty folder and put a trivial html file in it.
2. Serve the page using http-server.
3. Load the page in Chrome or Firefox (http://localhost:8080/<filename>)
4. Check connections using port 8080:
`lsof -i tcp:8080 -P -R`

Consistently I see something like the following:
`lsof -i tcp:8080 -P -R`
`COMMAND   PID  PPID   USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME`
`chrome   2632  1739 <uname>  638u  IPv4 5243565      0t0  TCP localhost:55476->localhost:8080 (ESTABLISHED)`
`node    18740 27348 <uname>   12u  IPv4 5243353      0t0  TCP *:8080 (LISTEN)`
`node    18740 27348 <uname>   13u  IPv4 5243566      0t0  TCP localhost:8080->localhost:55476 (ESTABLISHED)`

This pattern is consistent, and I see even more connections opened when serving a real page.  The ports change each time.

Is this expected behavior?  Any idea what these other connections are for?

Thanks,
-Ryan

**Comment by vincent178** [comment]
This is expected. This is how tcp works, open a tcp connection requires remote-ip:remote-port:local-ip:local-port.

**Comment by thornjad** [comment]
This expected behavior since this is an HTTP server, nothing would be able to happen without connections like this.
