### ISSUE TITLE
Need to set pass phase in ssl mode.

### ISSUE THREAD

**Issue by iamdenny** [http-party/http-server#456]
http-server provide ssl. it's the good thing. but I can't set the pass phase up.
My ssl cert has pass phase for security.
Please provide that I can put pass phase using http-server.

Thank you.

**Comment by thornjad** [comment]
Someone else correct me if I'm wrong, but I'm not sure `http-server` can support TLS/SSL pass phrases because https is internally handled by `union`, and it looks like they don't support passphrases.

See flatiron/union#58

**Comment by thornjad** [comment]
Closing as a duplicate of #162
