### ISSUE TITLE
.wasm (application/wasm) is served with charset

### ISSUE THREAD

**Issue by JoelEllis** [http-party/http-server#480]
this should not happen.

**Comment by nickolay** [comment]
This works for me with ecstatic 4.0.0 - probably thanks to https://github.com/jfhbrook/node-ecstatic/issues/220

**Comment by art-in** [comment]
using [light-server](https://www.npmjs.com/package/light-server) as a workaround for now, it serves wasm files with correct content type.

**Comment by tschoartschi** [comment]
Any update on this issue? Would be great to serve `wasm` files which are accepted by the browser 🙂

**Comment by aminya** [comment]
> using [light-server](https://www.npmjs.com/package/light-server) as a workaround for now, it serves wasm files with correct content type.

Thanks. It works perfectly:
```
light-server --serve . --open
```

**Comment by rhysd** [comment]
What is blocking this issue?

**Comment by zbynek** [comment]
@rhysd 
> What is blocking this issue?

The problematic code is in ecstatic, so the first step is to inline ecstatic (bigger change, scheduled for next release https://github.com/http-party/http-server/pull/693), then it should be just a one-line fix

**Comment by rhysd** [comment]
@zbynek Thank you for the update. I'll wait for next release and use other HTTP server for serving Wasm files meanwhile.

**Comment by martian17** [comment]
Ecstatic seems to be deprecated and no longer maintained, and this issue still persists 5 years later. 
Is http-server also dead? Can I contribute in any way if not?
The issue in question from Ecstatic: https://github.com/jfhbrook/node-ecstatic/issues/259
