### ISSUE TITLE
.mjs mimetype support

### ISSUE THREAD

**Issue by bjesuiter** [http-party/http-server#484]
.mjs ECMA Script Module files are served with `application/octet-stream` MIME Type 
instead of `text/javascript`, so the modules do not get imported in Chrome because of this error: 

> :8080/counter.mjs:1 Failed to load module script: The server responded with a non-JavaScript MIME > type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

Can you serve these files with the correct mime type please? Sounds like a pretty minor change :)

**Comment by BigBlueHat** [comment]
There's sadly a tangle of MIME-related dependencies to untangle. The underlying library dropped support for features we were using, so now we either need to re-implement them, drop them, or find other libraries to delegate the feature through...

Once we find the way through these woods, address this should indeed be trivial.

**Comment by neoeno** [comment]
Following the workaround (solution?) here got this working for me.

https://github.com/indexzero/http-server/pull/448#issuecomment-403267469

**Comment by thw0rted** [comment]
Is there currently a way to declare custom MIME type mappings?  If so, can somebody please a) document it in the README, or b) explain it briefly here so I can write up a PR with improved docs?

**Comment by Joao-Pedro-S** [comment]
You can use the mime-types from a JSON file, that would allow us to have more control and would probably also fix issue #623

**Comment by thornjad** [comment]
This _should_ be fixed by #693, I'm leaving this open for now so it gets checked after that merges.

**Comment by thornjad** [comment]
This appears to be fixed on `master`, please re-open if this is not the case.
