### ISSUE TITLE
Allow ES2015+ syntax

### ISSUE THREAD

**Issue by thornjad** [http-party/http-server#492]
Style linting (and therefore `npm test` and Travis) does not currently allow ES2015, even though Node fully supports it at this point, and an upgrade has a lot of real benefits; the first that comes to mind is `const` and `let`. ES2017 also adds async/await, which I have found extremely useful.

I see two ways we can go forward with this, we can either refactor http-server into ES2015+, or we can simply allow ES2015+ additions (like #491). Refactoring could be nice (I like refactoring), but would probably require a lot of existing PRs to be refactored as well. But this could just be shallow refactoring like switching `var`s to `let` and `const`. Simply allowing ES2015+ to pass tests, on the other hand, would allow it to be added in PRs and everything could be refactored piecemeal.

In either case, we should probably also bump up the versions of Node that Travis tests on, as well as decide on a new linter (common-style is deprecated in favor of eslint-config-populist).

**Comment by BigBlueHat** [comment]
👍 to the piecemeal approach. Lower risk and progressive improvement. I'm also fine with switching to a more up-to-date linter--but we can chat that in #497 and/or #494. 😄
