### ISSUE TITLE
Upgrade to latest ecstatic

### ISSUE THREAD

**Issue by thornjad** [http-party/http-server#518]
As of right now, ecstatic is at version 4.1.0, but we're still requiring only 3.3.0 on master. We need to make sure there are no breaking changes and upgrade, probably requiring `^4.x.x`.

This will fix #461 and #512.

**Comment by iTakeshi** [comment]
We should use ecstatic >= 4.1.2 because of an audit report https://npmjs.com/advisories/830

**Comment by stefanhuber** [comment]
![grafik](https://user-images.githubusercontent.com/5379359/56946145-9b02e480-6b29-11e9-8e6f-acdc91b7f331.png)

**Comment by Blackbaud-SteveBrush** [comment]
I'm getting `No matching version found for ecstatic@^3.0.0` after a clean install?

**Comment by lexzhukov** [comment]
> I'm getting `No matching version found for ecstatic@^3.0.0` after a clean install?

I'm having the same issue.

**Comment by Blackbaud-SteveBrush** [comment]
Issue: https://github.com/indexzero/http-server/issues/521

**Comment by thornjad** [comment]
Due to near-impossibilities with upgrading to ecstatic v4 and the fact that ecstatic is now dead, this issue is replaced by #568
