### ISSUE TITLE
it does not work when i reload the browser after navigating to a route.

### ISSUE THREAD

**Issue by NikitaPooja** [http-party/http-server#519]
In angular 7, On running the dist on local machine , for the first time web page is loading. And when on reloading or hit the url, the page throwing the error.

I am used this link to run on the local machine

How to run the Dist Folder on Local Machine in Angular 6?

On Reload and for hit the url I am using .htaccess file. but Its not work.

I took the template build with command ng build --prod

I changed in index.html href="/browser/"

For run on the local machine I am used http-server.

First install the package globally using command

npm install http-server -g.

Then inside the project directory(in the terminal) just run

http-server dist/.
For the first time web page is loading on the local machine and when on reloading or hit the url, the page throwing the server error.

**Comment by thornjad** [comment]
@NikitaPooja what is the error you're getting?

**Comment by rofrol** [comment]
I got the same. It does not support SPA.

**Comment by thornjad** [comment]
@rofrol could you share the error you're seeing?

**Comment by rofrol** [comment]
No error, it just does not direct you to index.html for routes. This works for me with nginx:

```
events {
	worker_connections 768;
}

http {
	server {
		# Enable static gzip
		gzip_static on;
		gunzip on;

		# Disable dynamic compression (optional, and not recommended if you're proxying)
		#gzip off;

		#sendfile on;

		listen 8080 default_server;
		listen [::]:8080 default_server;

		root /home/user/projects/project1;

		location / {
			try_files $uri /index.html;
		}
	}
}
```

**Comment by thornjad** [comment]
@rofrol you are correct that `http-server` does not support fallback paths in the manner of `try_files`. However, you can use `404.html` to sort-of support SPA. See #318 and #80.

@NikitaPooja is the error you're seeing when you say "the page throwing the server error" actually a 404 error, or is it an actual server error?

**Comment by rofrol** [comment]
@thornjad Great, it works with SPA:

`http-server --gzip --proxy http://localhost:8080?`

**Comment by thornjad** [comment]
Oh yes that's a good hack too! We've got that coming into the README in #513!

**Comment by thornjad** [comment]
Proxy redirect is now documented in the readme, as added by #513

**Comment by rmannibucau** [comment]
Hi, not sure what's the '?' hack does but it seems it does not work with a backend returning 404 (was it working due to the URL shape?).
Any hope we get a default redirect on 404 from the proxy?

**Comment by Lxrd-AJ** [comment]
I wonder which is recommended `--proxy http://localhost:8080?` or `--proxy http://127.0.0.1:8080?`
So far, I've found `--proxy http://127.0.0.1:8080?` to be unambiguous and should this be reflected in the README.md?

**Comment by thornjad** [comment]
@Lxrd-AJ those are the same thing

**Comment by thornjad** [comment]
@rmannibucau see https://github.com/http-party/http-server/pull/369#issuecomment-327291011

**Comment by rmannibucau** [comment]
@thornjad so maybe readme should be updated to mention proxying is incomplete and not intended for general purpose usage since for a dev server it is a common required feature?

**Comment by Lxrd-AJ** [comment]
> @Lxrd-AJ those are the same thing

Yes they are but `--proxy http://localhost:8080?` fails when visiting the browser via `http://127.0.0.1:8080` but not vice versa

**Comment by isaacnewtonaranas** [comment]
> No error, it just does not direct you to index.html for routes. This works for me with nginx:
> 
> ```
> events {
> 	worker_connections 768;
> }
> 
> http {
> 	server {
> 		# Enable static gzip
> 		gzip_static on;
> 
> 		listen 8080 default_server;
> 		listen [::]:8080 default_server;
> 
> 		root /home/user/projects/project1;
> 
> 		location / {
> 			try_files $uri /index.html;
> 		}
> 	}
> }
> ```

REALLY WORKING ON NGINX thanks for the help!!!
