### ISSUE TITLE
Feature request: show server settings info at start

### ISSUE THREAD

**Issue by pintux** [http-party/http-server#529]
**Do you want to request a *feature* or report a *bug*?**
feature

**If the issue is a bug report, please provide the steps to reproduce it. Please include the actual command causing the issue if applicable.**

**What did you expect to happen?**

**What actually happened? Please include the actual error trace and / or stack trace if applicable.**

**If the issue is a feature request, what is the motivation / use case for it?**
It would be nice to have a minimal recap of the server settings / options passed when server starts. For example, for a command like the following:

http-server -c-1 --cors

At start, it could be nice to have an output like the following:

```sh
Starting up http-server, serving ./
CORS enabled
Cache disabled

Available on:
  http://127.0.0.1:8081
  http://172.20.10.2:8081
  http://172.20.10.4:8081
```
**Tell us about your environment**
- **http-server version:**
- **Platform:**

**Other information (related issues, suggestions for a fix, etc):**

**Comment by kmjayadeep** [comment]
Can I take this up?

**Comment by ColtonHerrod** [comment]
I'd like to tackle this if its still outstanding.  Looks like the available IPs/ports are being logged, but the options aren't.
