### ISSUE TITLE
Unexpected end of JSON input while parsing near '...pendencies":{"he":"^0'

### ISSUE THREAD

**Issue by lanserdi** [http-party/http-server#552]
**Do you want to request a *feature* or report a *bug*?**

**If the issue is a bug report, please provide the steps to reproduce it. Please include the actual command causing the issue if applicable.**

**What did you expect to happen?**

**What actually happened? Please include the actual error trace and / or stack trace if applicable.**

**If the issue is a feature request, what is the motivation / use case for it?**

**Tell us about your environment**
- **http-server version:**
- **Platform:**

**Other information (related issues, suggestions for a fix, etc):**

**Comment by thornjad** [comment]
I'm going to close this for now since there's no description. Please do reopen after completing the template!
