### ISSUE TITLE
Failed to load module script: The server responded with a non-JavaScript MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

### ISSUE THREAD

**Issue by devvpm** [http-party/http-server#555]
Failed to load module script: The server responded with a non-JavaScript MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

I get this error while loading a javascript file as a module.

<script type="module" src="js/app_vue.js"></script>

How to resolve this issue?

**Comment by thw0rted** [comment]
I realize this was months ago, but are you sure the file is there?  `http-server` should send the correct MIME type based on extension, so if `js/app_vue.js` exists then it should be served as `application/javascript`.  Try loading that file directly and watch the response in the developer tools network tab.

**Comment by thornjad** [comment]
@devvpm could you make sure you're on the latest version of http-server, then try out 
```
$ curl -v http://localhost:8080/js/app_vue.js
``` 
and see what http-server is saying the `Content-Type` is? I wonder if this may be due to the `type="module"`

**Comment by thornjad** [comment]
This should be fixed on v13, please reopen if this is not the case
