### ISSUE TITLE
"Corrupted Content Error" on default page (/)

### ISSUE THREAD

**Issue by P1100** [http-party/http-server#556]
`Corrupted Content Error

The site at http://127.0.0.1:8080/ has experienced a network protocol violation that cannot be repaired.`

Response is 302, with "//" location. On the other hand, the URL "127.0.0.1:8080/index.html" works.

**Comment by pierreraii** [comment]
Duplicate of https://github.com/http-party/http-server/issues/525

**Comment by thornjad** [comment]
That's correct, this is a duplicate of #525
