### ISSUE TITLE
how to stop http-server

### ISSUE THREAD

**Issue by bluelemonade** [http-party/http-server#558]
hello,

I use the http-server on kiosk apps on windows with 
start /min http-server ./release -p 8080 -s

how can stop the server?

**Comment by thornjad** [comment]
I'm not familiar with kiosk apps, do you lose access to the server after starting it? If you still have access, `SIGTERM` will kill it.

**Comment by thornjad** [comment]
http-server now sets its own process title, so you can send a `SIGTERM` or similar to `http-server` to kill it.

**Comment by openmindculture** [comment]
How to find the process? `ps` does not list anything related to `server`, `npx` or `npm`. Similar [StackOverflow question](https://stackoverflow.com/questions/38933458/how-can-i-stop-the-http-server-downloaded-using-npm-install-http-server) answers did not work for me either.
