### ISSUE TITLE
--port is broken

### ISSUE THREAD

**Issue by johnstonmatt** [http-party/http-server#566]
**Do you want to request a *feature* or report a *bug*?**

**If the issue is a bug report, please provide the steps to reproduce it. Please include the actual command causing the issue if applicable.**

`http-server --port 3001`

**What did you expect to happen?**

Server should treat `http-server --port 3001` exactly like `http-server -p 3000`

I actually made the PR that did this. It happened here: https://github.com/http-party/http-server/pull/468

**What actually happened? Please include the actual error trace and / or stack trace if applicable.**

`http-server` uses the default port: 3000

**If the issue is a feature request, what is the motivation / use case for it?**

**Tell us about your environment**
macOS

- **http-server version:**
0.11.1
- **Platform:**
macOS
**Other information (related issues, suggestions for a fix, etc):**

**Comment by johnstonmatt** [comment]
@BigBlueHat could you please let me know how I might fix this issue? I think the new argv parser is broken

**Comment by x4th** [comment]
I haven't been able to replicate this on Ubuntu 18.04.3.

**Comment by johnstonmatt** [comment]
@x4th I have fixed an error in the issue description, are you using `-p` or `--port` ? I am able to configure the port using `-p` but not with `--port`

**Comment by x4th** [comment]
Using --port.
![Screenshot from 2019-10-11 18-27-57](https://user-images.githubusercontent.com/12177451/66668384-70c75e00-ec55-11e9-93c0-4a8730d9a73a.png)

**Comment by johnstonmatt** [comment]
@x4th thanks for your help! May I ask which version of http-server are you using?

**Comment by x4th** [comment]
I just cloned it from here, master branch, version 0.11.1.

**Comment by johnstonmatt** [comment]
@x4th by cloning this repo, I also have no issue. However after installing it via `npm` the issue is present

**Comment by morenoh149** [comment]
first thing I found on osx. I can reproduce. -p works find though

**Comment by Leedehai** [comment]
From @johnstonmatt's comment, a new release on NPM is needed? The latest one on NPM was 2 years ago.

**Comment by thornjad** [comment]
This _should_ be fixed now, please reopen if this is still happening on v13
