### ISSUE TITLE
-o cannot open browser in version 0.11.1

### ISSUE THREAD

**Issue by bndynet** [http-party/http-server#570]
From README.md

**-o [path] Open browser window after starting the server. Optionally provide a URL path to open. e.g.: -o /other/dir/**

Using `http-server -o /site/` cannot open browser automatically.

**Tell us about your environment**
- **http-server version:** 0.11.1
- **Platform:** macOS Mojave

**Comment by bbortt** [comment]
In my case it does open a windows explorer when supplying a `[path]` :D

**Comment by soulfresh** [comment]
This is not working for me with `http-server 0.11.1` and macOS Mojave either. We've tried Node `10.16` and `12.13` and `8.14`.

**Comment by T-igra** [comment]
workaround:
http-server -o http://127.0.0.1:8080/index.html

**Comment by moos** [comment]
`-o` also not working for me - same version - nor the workaround!

**Comment by thornjad** [comment]
@Moos am I reading your comment right that this is fixed correctly in v0.12.0?

**Comment by bndynet** [comment]
Confirmed, it works in v0.12.
