### ISSUE TITLE
--log-ip not working

### ISSUE THREAD

**Issue by cyqsimon** [http-party/http-server#578]
On Github your documentation includes a '--log-ip' option. However, this option is neither found in the documentation on [NPM's page](https://www.npmjs.com/package/http-server), or in the terminal's help text (http-server -h). Nor does including this option in execution actually do anything.

I did see some issues from three years ago that asked for this feature, and that it was later added in #501 . So was this feature later removed for some reason? Or was it somehow dropped by mistake?

**Comment by thornjad** [comment]
Unfortunately our releases have been lagging the master branch quite a bit, we're working on making a new release to npm soon, which will include the `--log-ip` option!

I'm going to close this issue for now but feel free to continue commenting, and re-open if you find `--log-ip` is present but non-functional.

**Comment by cyqsimon** [comment]
I shall wait patiently then. Thanks for your time!
