### ISSUE TITLE
http-server 0.12.0: index.html as default file is not working

### ISSUE THREAD

**Issue by AJLoveChina** [http-party/http-server#587]
**Do you want to request a *feature* or report a *bug*?**
BUG

**If the issue is a bug report, please provide the steps to reproduce it. Please include the actual command causing the issue if applicable.**

just in the windows CMD interface, type: 
`http-server -p 8080`

**What did you expect to happen?**
If there is a file named `index.html` in the current directory, it will be served as the default file when we access ` http://localhost:8080`, but it is not working on http-server@0.12.0 

Otherwise, if we rollback to http-server@0.9.0, it works!
I thought this feature is removed from @0.12.0, but when I come to the README.md, it still says that
> index.html will be served as the default file to any directory requests.

Which is right? Update docs or add the feature?

**Comment by thornjad** [comment]
What does http-server output to the cmd prompt, and what do you see in the browser when this happens? Do you see a listing of files or get a 404 error?

**Comment by AJLoveChina** [comment]
Amazing, yesterday it's not working, but today it works on version#0.12.0.
@thornjad  thank you for reply
