### ISSUE TITLE
Windows 7 compatibility?

### ISSUE THREAD

**Issue by Mirv** [http-party/http-server#593]
**bug**

**If the issue is a bug report, please provide the steps to reproduce it. Please include the actual command causing the issue if applicable.**

cd C:\Users\mirvdesign\AppData\Roaming\npm\node_modules\http-server\bin 
http-server c:\Sites\dice

**What did you expect to happen?**

Server to start or do anything

**What actually happened? Please include the actual error trace and / or stack trace if applicable.**

'http-server' is not recognized as an internal or external command, operable program or batch file.

**Tell us about your environment**
- **http-server version:** latest
- **Platform:** windows 7 with ubuntu add on to all npm
- npm@6.4.1 

**Other information (related issues, suggestions for a fix, etc):**

At first I thought it was a PATH location issue.  So I went to the bin folder holding the http-server file and fed it my js files directory to serve.

**Comment by thornjad** [comment]
How did you install http-server? Are you trying to run it in WSL or in the regular CMD?

**Comment by thornjad** [comment]
I'm going to close this for now since this seems to be an installation and/or path lookup problem, rather than an issue with this project. But I'll keep trying to help if you can post more info!

**Comment by Mirv** [comment]
NPM sorry I dropped off there ... it's not path issue, confirmed that before I posted.

**Comment by thornjad** [comment]
The `not recognized as an internal or external command` means it is probably a path issue, just not one that's been found yet. If you `echo %PATH%` does it contain the right directories? What is the exact command you used to install, and what was the output? Does the same thing happen if you try to install other packages from npm?

**Comment by Mirv** [comment]
I feel like you are right - but I'm executing from directly the http-server file resides (it's not an exe, but perhaps my understanding is off there)

```
C:\Users\mirvdesign\AppData\Roaming\npm\node_modules\http-server\bin>http-server C:\Sites\diceLib
'http-server' is not recognized as an internal or external command,
operable program or batch file.
```

Further ... the PATH result ... trimmed a bunch out of it ... hanging out at the end

```
C:\Users\mirvdesign\AppData\Roaming\npm\node_modules\http-server\bin>PATH
PATH=C:\Cygwin64\bin;C:\Ruby26-x64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\P
rogram Files\PuTTY\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;;C:\Users\mirvdesign\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\mirvdesign\AppData
\Roaming\npm\node_modules\vue-cli\bin;C:\Users\mirvdesign\AppData\Roaming\npm\node_modules\http-server\bin
```

**Comment by Mirv** [comment]
With the http-server included - same results ...

```
C:\Users\mirvdesign>PATH
PATH= ... C:\Users\mirvdesign\AppData\Roaming\npm\node_modules\http-server\bin;C:\Users\mirvdesign\AppData\Roaming\npm\node_modules\
http-server\bin\http-server
```

**Comment by thornjad** [comment]
I'm not super familiar with how Windows looks for or runs programs, but does it work if, while in `C:\Users\mirvdesign\AppData\Roaming\npm\node_modules\http-server\bin` you use `start http-server`? I haven't used Windows in a few years, so I'm a bit rusty.

Also have you tried restarting the command prompt? That solves path issues sometimes.

**Comment by Mirv** [comment]
Yes, yes & no results :(

I used another package though - so it's ok

**Comment by thornjad** [comment]
As far as my knowledge goes, the fact that `start http-server` works confirms it's a path issue, or at the least, its an issue with npm. I'm afraid we're at the limit of my Windows knowledge though, I'm not sure what else to look at 🙁

**Comment by Gesugao-san** [comment]
`node .\node_modules\http-server\bin\http-server`
