### ISSUE TITLE
Can't display files named like "%"

### ISSUE THREAD

**Issue by zhmushan** [http-party/http-server#603]
![image](https://user-images.githubusercontent.com/24505451/74167006-862fb180-4c62-11ea-9ce9-d6f364dfc621.png)

**Comment by thornjad** [comment]
That is an unorthodox filename, but I believe it should be valid. Apache seems to handle this just fine. I don't have time to look into this at the moment, but welcome PRs!

**Comment by zhmushan** [comment]
I don't know where you handled `req.url`. (I'm not familiar with these node modules

**Comment by thornjad** [comment]
After more investigation, I believe http-server is handling this correctly; `%` is an invalid filename, which is a malformed URI, which is a client error.
