### ISSUE TITLE
Can't use 0.0.0.0 address

### ISSUE THREAD

**Issue by cilphex** [http-party/http-server#615]
**Steps to reproduce the issue, if applicable. Include the actual command and output and/or stack trace.**

```sh
http-server -a 0.0.0.0 .
```

**What did you expect to happen?**

I expected to be able to serve pages from the `0.0.0.0` address, but instead it serves from `127.0.0.1`

```sh
02:32 PM my-project: http-server -a 0.0.0.0 .
Starting up http-server, serving .
Available on:
  http://127.0.0.1:8080
  http://127.0.0.3:8080
  http://10.0.0.189:8080
  http://10.128.1.14:8080
```

**If the issue is a feature request, what is the motivation / use case for it?**

Sometimes you'd like to expose `0.0.0.0` directly, rather than `127.0.0.1`. For example, it is [necessary for using in google cloud run](https://cloud.google.com/run/docs/troubleshooting#listen_address):

> A common reason for Cloud Run services failing to start is that the server process inside the container is configured to listen on the localhost (127.0.0.1) address. This refers to the loopback network interface, which is not accessible from outside the container and therefore Cloud Run health check cannot be performed, causing the service deployment failure.
> 
> To solve this, configure your application to start the HTTP server to listen on all network interfaces, commonly denoted as 0.0.0.0.

For this reason, `http-server` can't be used as a basic server within Google Cloud Run.

**Tell us about your environment**
- **exact http-server version:**
0.12.1
- **Node version:**
13.3.0
- **Platform:**
macOS / Docker

**Other information (related issues, suggestions for a fix, etc):**

The overwrite happens [in the executable](https://github.com/http-party/http-server/blob/454851c32065b16787821b0e27ec10298b163f09/bin/http-server#L164), but I'm not sure if there's similar overwrites in underlying libraries that `http-server` utilizes.

If it is widely preferable to have `0.0.0.0` mean `127.0.0.1` by default, maybe there should be an option to override?

What is the reasoning for it not even being possible to serve from `0.0.0.0` if you want to?

**Comment by skyward-luke** [comment]
bump

**Comment by jianshen92** [comment]
This causes cloud run to fail

**Comment by jianshen92** [comment]
@skyward-luke Have you tried your fix by deploying to Cloud Run? It doesn't seem to work for me.
