### ISSUE TITLE
optimist using vulnerable version of minimist

### ISSUE THREAD

**Issue by marizmelo** [http-party/http-server#617]
Low:  Prototype Pollution 
│ Package       │ minimist  
│ Patched in    │ >=0.2.1 <1.0.0 || >=1.2.3  
│ Dependency of │ http-server [dev]     
│ Path          │ http-server > optimist > minimist 
│ More info     │ https://npmjs.com/advisories/1179

**Comment by thornjad** [comment]
Duplicate of #614
