### ISSUE TITLE
How to start a cmd prompt http-server with custom title

### ISSUE THREAD

**Issue by celestale** [http-party/http-server#620]
Start the server with a Bat file containing:
`start cmd /k "TITLE Hosting Server - DO NOT CLOSE & http-server"`

Cmd prompt title gets changed back into http-server, overwriting the existing title `Hosting Server - DO NOT CLOSE`. How can we change the title?

**Comment by thornjad** [comment]
I don't know anything about cmd prompt, but could you try setting the title _after_ starting http-server?

**Comment by thornjad** [comment]
I'm going to close this since this doesn't look like an issue with http-server, but please do keep commenting, and re-open if it turns out to be a bug in this project
