### ISSUE TITLE
TLS/SSL doumentation does not work

### ISSUE THREAD

**Issue by coreybruce** [http-party/http-server#621]
**Steps to reproduce the issue, if applicable. Include the actual command and output and/or stack trace.**

TLS/SSL documentation does not work due to it not being able to  prove that the security certificate is not trusted.

https://i.imgur.com/Ta2RLqi.png

https://i.imgur.com/OfTpCsD.png

I did as the documentation said and did `openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem`

than as you can see added the argument on the http-server command

**What did you expect to happen?**
 Run a web server with SSL HTTPS

**If the issue is a feature request, what is the motivation / use case for it?**

**Tell us about your environment**
- **exact http-server version:**
0.12.1
- **Node version:**
NPM 6.14.4
- **Platform:**
Linux
**Other information (related issues, suggestions for a fix, etc):**

**Comment by luisgrappi** [comment]
It's not a problem with the server, just your browser/OS doesn't recognize your certificate as a valid certificate. For security reasons, browsers and OS's only recognize certificates issued by trusted corps (like Let's Encrypt or Digicert for example).

For your issue, you have two ways to solve it:
- If you want to see https working properly only in localhost you can tell your computer to trust it by doing the steps described in [this issue](https://superuser.com/questions/1083766/how-do-i-deal-with-neterr-cert-authority-invalid-in-chrome)

- If you have a domain and want an trusted certificate you can do it for free [here](https://www.sslforfree.com/)

**Comment by thornjad** [comment]
As far as I know, that's correct, the problem is that your OS isn't trusting the certificate, not that http-server isn't serving it. Please reopen if this is not the case
