### ISSUE TITLE
Add man page to the npm artifact

### ISSUE THREAD

**Issue by badeball** [http-party/http-server#625]
**Steps to reproduce the issue, if applicable. Include the actual command and output and/or stack trace.**

```
$ npm install -g http-server
```

**What did you expect to happen?**

For the man page to be installed.

``` 
$ man http-server
No manual entry for http-server
```

**Tell us about your environment**
- **exact http-server version:** v0.12.2
- **Node version:** v13.8.0
- **Platform:** Arch Linux

**Other information (related issues, suggestions for a fix, etc):**

I guess you only need to add the directory to the files-array in package.json and then npm is supposed to handle the rest - is that be correct?

**Other information (related issues, suggestions for a fix, etc):**

**Comment by thornjad** [comment]
Yep that'll do it. Nice quick catch! Guess I'll do the ol' quick patch release.
