### ISSUE TITLE
"Accept-Ranges: bytes"  is missing from static file endpoints

### ISSUE THREAD

**Issue by nom3ad** [http-party/http-server#627]
[Accept-Range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges) header is missing while calling HEAD/GET method to a static file path.

![Screenshot_20200507_161736](https://user-images.githubusercontent.com/19239479/81286182-479d6d80-907e-11ea-9c43-b6535c3e3f0b.png)

But http-server supports `Range` header to access partial content.  And `Accept-Range` is only present in  such response.
![Screenshot_20200507_162556](https://user-images.githubusercontent.com/19239479/81286891-70723280-907f-11ea-91b9-430c23ea5992.png)

Some clients checks this header to resume interrupted request.

**Tell us about your environment**
- **exact http-server version:** 0.12.3
- **Node version:** 10.18.1
- **Platform:** Linux

**Comment by RavinduL** [comment]
#536  addresses this by including `Accept-Ranges: bytes` with every response.  
Merged to be released in `v0.13.0`.

**Comment by thornjad** [comment]
Should be fixed by #536, please reopen if this is not the case
