### ISSUE TITLE
Ability to set reject unauthorized to false when backend server is running with self signed certificates

### ISSUE THREAD

**Issue by arkasaha2** [http-party/http-server#638]
http-server: v0.12.1
node: v12.13.0

I have node js server which has rest api running on https by some self signed certificates. And a FE that is hosted using http-server.

When any request is made to backend, I get this error: **unable to verify the first certificate**

Which I think is due to the self signed certificates I am using. It would be nice if we have an option for setting reject-unauthorized to false.

**Comment by thornjad** [comment]
Possibly addressed by #720
