### ISSUE TITLE
[feature] remove the dependence of ecstatic

### ISSUE THREAD

**Issue by brizer** [http-party/http-server#639]
The `node-ecstatic` is [unmaintained](https://github.com/jfhbrook/node-ecstatic/issues/259).
And It has [security problem](https://github.com/advisories/GHSA-9q64-mpxx-87fg), but [not prepare to fix it](https://github.com/jfhbrook/node-ecstatic/issues/268).

So please replace it.

**Comment by thornjad** [comment]
Duplicate of #568, working on it in #631
