### ISSUE TITLE
Files with different letter case displays only one file.

### ISSUE THREAD

**Issue by trishantpahwa** [http-party/http-server#643]
**Steps to reproduce the issue, if applicable. Include the actual command and output and/or stack trace.**

I have a few files with the same name but different letter case. Like `oNe.html, one.html, One.html, ONe.html`, within the same folder. These files appear separate in the folder view. But, when I host using `http-server` in the CLI, it only shows a single file called one.html.

I understand HTTP is not case sensitive. But, this seems to be an issue right here. Might have some solution, for this.

**What did you expect to happen?**
Multiple files should be displayed in the browser.

**If the issue is a feature request, what is the motivation / use case for it?**
Just came across this. Thought of informing the community.
**Tell us about your environment** Linux
- **exact http-server version:** v0.12.3
- **Node version:** v10.21.0
- **Platform:**

**Other information (related issues, suggestions for a fix, etc):**

**Comment by Joao-Pedro-S** [comment]
Well, they aren't really impossible. You can see that the encodeURI() does not destroy the case.
![image](https://user-images.githubusercontent.com/66487668/99811824-6e0b8d80-2b24-11eb-9b6c-66aaa8a2217d.png)

**Comment by Joao-Pedro-S** [comment]
Maybe it's a problem with the `fs` library.

**Comment by thornjad** [comment]
While URLs are technically case-insensitive, the underlying OS is case-sensitive (except Windows), so I consider this a bug

**Comment by SwitchRob** [comment]
This would be really useful as a startup option in my use-case, we mostly test our apps on IIS, however we do need to check they will also be okay if deployed to other environments where case-sensitivity of the OS is different.
