### ISSUE TITLE
Http-Server plus Homebridge-ui-x server causing domain issues

### ISSUE THREAD

**Issue by djgalati** [http-party/http-server#647]
so under my http-server running on my pi, I have 2 websevers, the homebridge web server that comes preinstalled with the OS and my http-server I have started. Both run at the same time on different ports but when I tie the IP to a DNS for my domain. it strictly connects to the homebridge web interface and not my HTTP server. I have no clue how to fix this.

**Comment by thornjad** [comment]
What ports are you running the two on? Is it open to the Internet, and if so, are there any port-forwarding issues at your router? That is, is the port that http-server is running on open to the Internet?
