### ISSUE TITLE
accept --hsts flag

### ISSUE THREAD

**Issue by lanterndev** [http-party/http-server#65]
Would you accept a pull request to accept an --hsts command line flag, which would implement this logic (from https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security ):

```
protected void Application_BeginRequest(Object sender, EventArgs e)
{
  switch (Request.Url.Scheme)
  {
    case "https":
      Response.AddHeader("Strict-Transport-Security", "max-age=31536000");
      break;
    case "http":
      var path = "https://" + Request.Url.Host + Request.Url.PathAndQuery;
      Response.Status = "301 Moved Permanently";
      Response.AddHeader("Location", path);
      break;
  }
}
```

**Comment by indexzero** [comment]
Yes. We would accept this :+1:

**Comment by skivvies** [comment]
Ooh, an answer! :P But now I'm no longer working with this project. Hopefully someone else will come along interested in implementing this for you. Best wishes.

**Comment by thornjad** [comment]
I'm going to close this for inactivity, but anyone is welcome to reopen and/or submit a PR for this!
