### ISSUE TITLE
Routes contains query string are not working(React Js).

### ISSUE THREAD

**Issue by ultimateakash** [http-party/http-server#653]
Command - http-server --proxy http://localhost:8080?
All Url working fine except the url having query string. 
example - http://localhost:8080/courses?keyword=software  // not working
Please help.

**Comment by thornjad** [comment]
This is a shortcoming of that proxy hack, it will rewrite everything after the host/port into query strings. You could maybe use JS to look for a `?` in the URL?

Ultimately, http-server doesn't officially support SPAs, they are better suited to more powerful server software like Apache.
