### ISSUE TITLE
Posibility to disable adding of forward slash

### ISSUE THREAD

**Issue by simplenotezy** [http-party/http-server#656]
**Steps to reproduce the issue, if applicable. Include the actual command and output and/or stack trace.**

My web app have disabled forward slashes, but I experience an infinite loop because http-server sends a 301 redirect to contain forward slash if it is not present in the URL. Once my app has been loaded, and detect a forward slash, it will redirect to the version that does not contain the forward slash, and in loop it goes...

**What did you expect to happen?**

Forward slash should be an optional setting that can be disabled.

**Tell us about your environment**
- **exact http-server version:** latest
- **Node version:** v12.10
- **Platform:** macos/linux

**Other information (related issues, suggestions for a fix, etc):**
https://github.com/http-party/http-server/issues/37

**Comment by thornjad** [comment]
This is already supported by `-i false`, please re-open if that option is broken

**Comment by thornjad** [comment]
Also duplicate of #539
