### ISSUE TITLE
Downloads index.html instead of serving it

### ISSUE THREAD

**Issue by alexeychikk** [http-party/http-server#657]
**Steps to reproduce the issue, if applicable. Include the actual command and output and/or stack trace.**

`http-server ./dist`

**What did you expect to happen?**

I expected to see rendered `./dist/index.html` web page in the browser. 
BUT instead browser opens save file dialog.

**If the issue is a feature request, what is the motivation / use case for it?**

**Tell us about your environment**
- **exact http-server version:** ^0.12.3
- **Node version:** 12.16.3
- **Platform:** Windows 10, Chrome 86.0.4240.75 (Official Build) (64-bit)

**Other information (related issues, suggestions for a fix, etc):**

**Comment by alexeychikk** [comment]
Fixed prepending the command with `npx` like this:
`npx http-server ./dist`

**Comment by thornjad** [comment]
@alexeychikk `http-server` and `npx http-server` should behave identically. How did you have it installed for the non-npx version?

**Comment by alexeychikk** [comment]
@thornjad I installed it with `npm i -D http-server`

**Comment by thornjad** [comment]
What does http-server --version output? I wonder if it's picking up an out-of-date globally-installed version.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by alexeychikk** [comment]
@thornjad 
```
PS D:\git\alexeychikk.github.io> http-server --version
http-server: The term 'http-server' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

```
PS D:\git\alexeychikk.github.io> npm run serve

> alexeychikk.github.io@1.0.0 serve D:\git\alexeychikk.github.io
> http-server --version

v0.12.3
```

**Comment by thornjad** [comment]
Hm, odd. Well I'm not sure what happened, and I have very little experience with Windows, so I don't know if there's any Windows-specific stuff going on there. I'm glad `npx` works! I'm partial to using `npx` most of the time anyway.

**Comment by izaleu** [comment]
I have the same issue, using npx did not fix it for me.

**Comment by zm3d3ni** [comment]
Try http://127.0.0.1:8080/index.html in windows

**Comment by vincentLW** [comment]
> I have the same issue, using npx did not fix it for me.

try clear the cache for localhost:8080

**Comment by Cosy-harks** [comment]
I had this issue when I searched localhost:8080

Issue gone when I searched localhost:8080/index.html

**Comment by yuvalkabeli** [comment]
In case someone still has trouble (I tried everything I found online and still got stumped) I found this command:
`http-server --proxy http://localhost:8080?`
once I did this it opened up an HTML page with a menu for all the files in my project with each one having a separate address.
It's definitely not the best solution, but if you run out of options try it out!

**Comment by goldingdamien** [comment]
I had a similar issue where using port 8080 was causing a download of file "download" to be downloaded with the contents of the html file.
I couldn't fix it with anything here, but it was fixed by changing to port 8081.
It would be nice if someone could provide a reason for this issue.
