### ISSUE TITLE
Maximum call stack size exceeded on installation

### ISSUE THREAD

**Issue by siddharthvp** [http-party/http-server#659]
**Steps to reproduce the issue, if applicable. Include the actual command and output and/or stack trace.**
```
$ node -v
v14.12.0
$ npm -v
6.14.8
$ npm i http-server
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/<USERNAME>/.npm/_logs/2020-10-14T16_05_57_538Z-debug.log
```
**What did you expect to happen?**

Expected http-server to install.

**Tell us about your environment**
- **exact http-server version:** -
- **Node version:** 14.14.0
- **Platform:** Ubuntu 16.04.4 LTS on WSL on Windows 10

**Other information (related issues, suggestions for a fix, etc):**

**Comment by thornjad** [comment]
Is there anything http-server related in the npm debug log?

**Comment by radicalEdward334** [comment]
Try clearing your NPM chache

https://stackoverflow.com/questions/40566348/maximum-call-stack-size-exceeded-on-npm-install

**Comment by siddharthvp** [comment]
> Is there anything http-server related in the npm debug log?

No. Indeed this may not be an issue with http-server itself. Closing.
