### ISSUE TITLE
How can we give space in path name

### ISSUE THREAD

**Issue by pratikgolchha** [http-party/http-server#660]
**Steps to reproduce the issue, if applicable. Include the actual command and output and/or stack trace.**

http-server <<path with space>>

**What did you expect to happen?**

It should take the complete version

**If the issue is a feature request, what is the motivation / use case for it?**

**Tell us about your environment**
- **exact http-server version:** Latest
- **Node version:**
- **Platform:**

**Other information (related issues, suggestions for a fix, etc):**

**Comment by thornjad** [comment]
I don't believe spaces are valid in URLs, does it work if you replaces the spaces with "%20"?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Joao-Pedro-S** [comment]
When the browser makes a HTTP request, the path is encoded: "<" is replaced as "%3E" and the white space as %20, we just need to decode the path from %20 to white space. We could use a `DecodeURL()` function

**Comment by J-P-S-O** [comment]
> When the browser makes a HTTP request, the path is encoded: "<" is replaced as "%3E" and the white space as %20, we just need to decode the path from %20 to white space. We could use a `DecodeURL()` function

So yes, spaces are valid, but encoded as hex (%xx).
