### ISSUE TITLE
Upgrade ecstatic

### ISSUE THREAD

**Issue by pburkindine** [http-party/http-server#666]
The version of ecstatic currently pinned (^3.3.2) has a security vulnerability and should be replaced with ^4.1.3 or better

https://snyk.io/vuln/SNYK-JS-ECSTATIC-540354

**Comment by zommerfelds** [comment]
Looks like this is being tackled in https://github.com/http-party/http-server/pull/631

**Comment by thornjad** [comment]
Duplicate of #568
