### ISSUE TITLE
http-server does not get PORT from process.env by default

### ISSUE THREAD

**Issue by duc-dev** [http-party/http-server#683]
My command: http-server dist -a mysite.com -S -C cert.pem -K key.pem -o
My .env file: PORT=8081

Expected: The url should be: https://mysite.com:8081

The result: https://mysite.com:8080

Environment:
- http-server: 0.12.3
- Node version: 14.4.0
- Platform: Windows 10

Other information: http-server does not get PORT from process.env.PORT by default

**Comment by duc-dev** [comment]
It seems that http-server does not read .env file.  I try using dotenv module and adding dotenv to http-server.js in order to load .env file and it works correctly, http-server can get the PORT from .env file

**Comment by thornjad** [comment]
That's correct that http-server does not read any `.env` file, if you export the `.env` into your environment, does it pick up the port correctly?

**Comment by thornjad** [comment]
Closing for now, please re-open if this turns out to be a bug in http-server

**Comment by zbynek** [comment]
> so http-server.js won't read the .env file

Correct.

> my docker-entrypoint.sh has this command - `http-server dist -p 3000 --cors -c1 -g`

You're passing the port 3000 explicitly, so that should ignore not just the `.env` file but also any `PORT` environment variable set inside the container.

**Comment by gursahibsahni** [comment]
> > so http-server.js won't read the .env file
> 
> Correct.
> 
> > my docker-entrypoint.sh has this command - `http-server dist -p 3000 --cors -c1 -g`
> 
> You're passing the port 3000 explicitly, so that should ignore not just the `.env` file but also any `PORT` environment variable set inside the container.

Great, thanks for the confirmation. Just for clarification , am trying to pass sensitive data and not the port. I’ll use the node command to run the server then.
