### ISSUE TITLE
Start the http-server command then get the download

### ISSUE THREAD

**Issue by ducccao** [http-party/http-server#686]
I've tried some commands and met some problems and there are
1. Command:  http-server
- I expected that the command will serve my index.html file, but the result is the download!
- Port 8080
- Image result
- Access URL:  http://192.168.2.230:8080
![1](https://user-images.githubusercontent.com/44729657/120113593-5c770280-c1a5-11eb-8124-4872cc00ab34.jpg)

2.  Then I try another port with the command: http-server -p 1212
- And it works normally

Question: Did I miss understanding something or is it a bug?

**Comment by TobiasUhmann** [comment]
In my case, I think it had something to do with my Vue SPA's URL routes not ending in `.html`.

Clearing the cache for `localhost:8080` solved the problem.

**Comment by thornjad** [comment]
Do you have anything else running on port 8080? It's possible something other than http-server is serving that file

**Comment by ducccao** [comment]
I don't have anything running on port 8080, and if I have, it will automatically turn to another port like 8081. Currently, it works normally, maybe at that time, I was running multiple tasks which were in conflict with http-server.

**Comment by vincentLW** [comment]
> In my case, I think it might have had something to do with my Vue SPA's URL routes not ending in `.html`.
> 
> Clearing the cache for `localhost:8080` solved the problem.

It works  thanks  a lot, man

**Comment by ducccao** [comment]
Oops, I met this problem again, so we should clear the cache every time we use
