### ISSUE TITLE
Automatically refresh when change in file(s) are detected?

### ISSUE THREAD

**Issue by alexkolson** [http-party/http-server#69]
I use `http-server` for local development and love it. Just wondering if there are any plans to have it automatically reserve files in which a change is detected. Not a major issue, just a question/enhancement request.

**Comment by patmigliaccio** [comment]
It seems this will only possible by either injecting a client-side script into all html pages or requiring the installation of a browser extension.

**Comment by thornjad** [comment]
Some documentation about restarting http-server on file change may be added by #527

**Comment by thornjad** [comment]
Since there's no server-side cache, this is already supported. Please re-open if this isn't the case.

**Comment by bonnebulle** [comment]
Maybe @alexkolson thinks about live reloading/refresh browser ?  (on file change)
(my answer is more a missing feature, than an issue)

I use an othe npm package as a live watcher (and proxy)
```browser-sync start --proxy "127.0.0.1:8080" --files "."```

If is not what you searching, sorry for reopening
thanks
