### ISSUE TITLE
WebAssembly.instantiateStreaming` failed because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error

### ISSUE THREAD

**Issue by insinfo** [http-party/http-server#690]
WebAssembly.instantiateStreaming` failed because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error

this is happening when I try to serve a simple html with webassembly, it seems that this web server is not serving the .wasm files with the correct MIMI type

https://github.com/insinfo/photon-test

**Comment by thornjad** [comment]
Is this issue included in #480 or is it distinct?

**Comment by thornjad** [comment]
Closing right now as a duplicate of #480, please re-open if this is not the case
