### ISSUE TITLE
Removing "hs" alias for http-server?

### ISSUE THREAD

**Issue by bengoshow** [http-party/http-server#695]
I have another command line tool that uses `hs` to run commands, but there is a conflict between that tool and http-server, which appears to be installed along with Node.js. Is there any way to remove or disable the `hs` alias directive as shown on https://github.com/http-party/http-server/blob/db66b17e28105d4fd6d41913cd5a7cbe7ba1528f/package.json#L82

**Comment by thornjad** [comment]
I'm on board for this, I think `hs` should be a user-defined alias if it's desired. Though I'd consider it a major change in case anyone is depending on this alias, meaning it would need to wait until a major release. I'll queue this into a new milestone to keep track of it.

**Comment by alexp1917** [comment]
this was a very convenient alias

**Comment by thornjad** [comment]
A better alternative to using an old version would be creating your own alias with `alias hs='http-server'`
