### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [http-party/http-server#699]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by thornjad** [comment]
Great idea on the security file, I didn't know that was a thing! I've just added on in beb48a52da8e35a7789dfeaf7f43cc3df6bc2d68. I could probably set up an http-server email for that sort of thing, but I just used my own for now. Hopefully spam doesn't pick up 🤞
