### ISSUE TITLE
How to run this as service

### ISSUE THREAD

**Issue by cheffNFT** [http-party/http-server#708]
I'm trying to run this httpserver as service but until now I can't
Are there any way to do that?
this is my current attempt on doing so

  GNU nano 4.8                                                              httpserver.service                                                                        
[Unit]
Description=Http Server
After=network.target

[Service]
ExecStart=ExecStart=/bin/bash -l -c "exec /home/myuser/httpserver.sh"
Restart=always
User=cardano
Environment=PATH=/usr/bin:/usr/local/bin
Environment=NODE_ENV=production
WorkingDirectory=/home/myfolder

[Install]
WantedBy=multi-user.target

httpserver.sh
http-server /home/myfolder/public

**Comment by thornjad** [comment]
I'm going to close this as it's not about http-server itself, but I'll try to help if I can!

What is in `httpserver.sh`? If you're okay with a possible delay before start, would it work to use `npx http-server /home/myfolder/public` instead of the script?
