### ISSUE TITLE
remembers old directories when serving on previous ports

### ISSUE THREAD

**Issue by brendajin** [http-party/http-server#71]
I once served a static file system locally on port 2002 using `-p`

Now I've killed the server and navigated to a different port. However, it's still serving from the same old directory if I try to use that port.

**Comment by thornjad** [comment]
@brendajin are you able to reproduce this on the latest version of `http-server`?

**Comment by thornjad** [comment]
This sounds like some overly-heavy caching by the browser, which can be stopped with the `-c-1`	option, which was broken but is fixed by #326
