### ISSUE TITLE
Is there an option for specifying the folder path to share out?

### ISSUE THREAD

**Issue by StingyJack** [http-party/http-server#710]
I'd like to include http-server as a dev dependency for a specific package/project, and have it share a folder that is a sibling of the folder that has the package.json.   In this example the `static files` folder is where I would want to share using http-server. 
```
$/project/package.json
$/project/node_modules/
$/staticFiles/
```

But since that exists outside of the project folder I have to install it http-server globally. This is not a terrible or difficult thing, but I was looking for a way to designate the folder to use and I dont see a parameter that looks obvious. Is there one that I'm just missing?

**Comment by thornjad** [comment]
Does it work to use `http-server ../staticFiles/`?

**Comment by StingyJack** [comment]
```
usage: http-server [path] [options]
```
🤦🏿
