### ISSUE TITLE
Use table format for README summary of commands

### ISSUE THREAD

**Issue by thornjad** [http-party/http-server#714]
As http-server has grown, the list of commands has as well. The README lists them all out as a list, but at this point it would be more readable as a table.

**Comment by RhnSharma** [comment]
I would like to take this one.
I have to present available options in a table, right?

**Comment by thornjad** [comment]
Probably! The real goal is to make the commands as readable as possible; a table is my best idea right now but if you have a better idea, go for it!

**Comment by wayiam** [comment]
Hey, I want to contribute on this issue as my First open source contribution. Please guide me.

**Comment by zbynek** [comment]
thanks for the PR, @wayiam  https://github.com/http-party/http-server/pull/715

**Comment by thornjad** [comment]
Completed in master
