### ISSUE TITLE
i want change the default file for directory request, not index.html

### ISSUE THREAD

**Issue by hisland** [http-party/http-server#754]
#### What's the problem this feature will solve?

i want change the default file for directory request, not `index.html`

#### Describe the solution you'd like

give me an option to set the file name

#### Alternative Solutions

or i can disable the feature, just list the files in my directory

**Comment by chris--jones** [comment]
Duplicate of #678, I've started a fix here which just requires some more testing / unit tests: https://github.com/chris--jones/http-server/tree/index-and-notfound

**Comment by fitcwill** [comment]
Catching up on this. Says closed as completed which was misleading at first. Is it not possible to close as duplicate?
