### ISSUE TITLE
Http to https redirect

### ISSUE THREAD

**Issue by catherineVoo** [http-party/http-server#765]
Hello,

Having a positive result in Lighthouse (devtools) PWA testing is currently not possible anymore: Lighthouse requests a http > https redirection to give a positive audit. A nice to have feature would be a simple option added when we start the server (like "--redirect-https" for example).

**Comment by thisIsTheFoxe** [comment]
Possible duplicate of:
- #273 
- #598
- #600

**Comment by thornjad** [comment]
Yeah I'm going to call this a duplicate of #273

**Comment by catherineVoo** [comment]
Thank you for the info. Maybe it's a good idea to add the info in the documentation ?
