### ISSUE TITLE
How to work around broken dependencies (colors.js)

### ISSUE THREAD

**Issue by RPGillespie6** [http-party/http-server#781]
`http-server` won't launch because of https://github.com/Marak/colors.js/issues/285

I tried downloading older versions of `http-server` but the issue persists.

How do I work around this? My pipeline is broken. Please consider locking in specific known-working versioned dependencies in `package.json` instead of just grabbing the latest which may pull in broken/malicious/woke/protest dependencies.

**Comment by DanielRuf** [comment]
You can use resolutions or patch-package to "fix" this as described at https://github.com/Marak/colors.js/issues/285#issuecomment-1008168237.

**Comment by thornjad** [comment]
Ah crap, not this again. At least this time colors isn't as integral to http-server as when ecstatic did this. Give me a little time to catch up this latest drama and I'll accept one of the two PRs for this.

**Comment by thornjad** [comment]
Merged #785, just going to see what the tests do (I know Node 17 has some problems) before tagging a release. I'll backport to v13 later today.

**Comment by DanielRuf** [comment]
@thornjad Node 17 and and other Node release with an odd major version number is not recommended in general as these are no LTS releases but short living test branches.

**Comment by thornjad** [comment]
That's why I haven't put it on a high priority, but I'd prefer to support it. They are more than just test branches, while not LTS, it is a proper full release. But its especially frustrating that it works fine in every local environment I've put it in, but gh-actions fails consistently.

**Comment by thornjad** [comment]
:tada: Published to npm! Check for versions v14.1.0 or v13.1.0

**Comment by NicholasBoll** [comment]
I see the [14.1.0 Github release](https://github.com/http-party/http-server/releases/tag/v14.1.0), but npm doesn't seem to have it yet :(

**Comment by thornjad** [comment]
npm has a lot of caching in place to deal with the enormity of the traffic it serves, so it might take a while, maybe even a few hours, to show up for everyone. I've verified it did publish though, so its just a matter of time!

**Comment by NicholasBoll** [comment]
I see it now. Thanks. I figured npm was behind with caching. After an hour I got a little worried.
