### ISSUE TITLE
Strange behavior in MacOS 

### ISSUE THREAD

**Issue by davidjpfeiffer** [http-party/http-server#782]
I have used this http server for years and never had any issues at all. All the sudden I went to install http-server on my new mac and I am unable to host a simple static HTML file. I am able to install the http-server package using NPM but then when I try to host a web server I see this strange behavior in terminal:

![Screen Shot 2022-01-09 at 12 15 49 PM](https://user-images.githubusercontent.com/8846738/148699384-cd37a115-23dd-4d91-9283-7fce0f69f14e.png)

#### Environment Versions

1. MacOS Monterey: 12.1
2. Node version: 16.13.1
3. NPM version: 8.1.2
4. http-server version: 14.0.0

#### Steps to reproduce

1. `npm i http-server`
2. `npx http-server`

#### Expected result

The web server gets hosted and the Terminal window shows network log info as usual

#### Actual result

The web server is not hosted and instead the terminal window spams endless unrecognizable characters as seen in the screenshot

#### Other information

I have tried using multiple different versions of the http-server package including versions 13.0.0 and much older versions but the behavior is the same. I tried using `sudo` when installing the http-server package but that did not change anything. I also tried giving my Terminal Full Disk Access and access to the Developer Tools but nothing I have tried changes the behavior.

**Comment by davidjpfeiffer** [comment]
Just in case this is helpful information, I am able to download the Angular CLI using NPM and then create a new Angular project and host it on a local web server no problem on this same computer.

**Comment by BitesizedLion** [comment]
This issue is due to the NPM module "colors", it's author went rogue and added an infinite for loop because he thought it would be funny.

**Comment by davidjpfeiffer** [comment]
@BitesizedLion thank you so much for responding, it was driving me crazy trying to figure out what was going on

**Comment by davidjpfeiffer** [comment]
Here is a news story about the incident https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/

**Comment by davidjpfeiffer** [comment]
If anyone else is impacted by this you can consider using https://www.npmjs.com/package/serve as an alternative

**Comment by mattdaviscodes** [comment]
Same problem.

**Comment by thornjad** [comment]
This is fixed in http-server v14.1.0 and backported to v13.1.0. It was indeed caused by Marak/colors.js#285, and we fixed it by switching out `colors.js` for `chalk`.
