### ISSUE TITLE
NPX Weird Terminal Output / Doesn't Work

### ISSUE THREAD

**Issue by x89-h** [http-party/http-server#784]
#### Environment Versions

1. Windows 11
1. Node version: v14.18.1
1. http-server version: presumed latest (using npx)

#### Steps to reproduce

I just ran `npx http-server dist -c-1`

#### Actual result

![image](https://user-images.githubusercontent.com/84206963/148707455-d00c8fe1-b64e-4081-b59b-40a9e3176044.png)

That image is worth a thousand words.

#### Other information

It worked fine yesterday, I am running the same command and have made no changes. I tried restarting my PC.

**Comment by x89-h** [comment]
Read up on it, apparently some selfish dev did this because he was upset that companies with a lot of money wouldn't give him any. Sounds like **_communism_** to me lmao. Also, seen it has kinda been reported. Good luck fixing it.

**Comment by thornjad** [comment]
FYI, fixed in http-server v14.1.0
