### ISSUE TITLE
what hell is going on ?

### ISSUE THREAD

**Issue by JohyC** [http-party/http-server#787]
#### Environment Versions

1. OS Type
![image](https://user-images.githubusercontent.com/38210128/148731668-10c5a734-eeb2-485e-ad18-0c089f817ce3.png)

1. Node version: `$ node --version`
![image](https://user-images.githubusercontent.com/38210128/148731702-868c8b48-0502-4497-8e7c-f0819c8b1065.png)

1. http-server version: `$ http-server --version`
I can`t use http-server --version!!!

#### Steps to reproduce

`$ http-server`

i got this!
![image](https://user-images.githubusercontent.com/38210128/148731815-fb6e2d72-4d4a-4bd6-a90b-ffd1035eca08.png)
 also i can`t use old!

**Comment by scottstanfield** [comment]
I'm getting garbage as well on macOS (using Alacritty) and node v16.13.1 (LTS)

![image](https://user-images.githubusercontent.com/280700/148732114-ae51eacd-e861-4044-a81c-0e6d9c6eb102.png)

Same results in Terminal. This is using a new M1 Pro.

**Comment by scottstanfield** [comment]
Zooming in...there are words in here like "TESTING"...I highlighted the word in the middle.

![image](https://user-images.githubusercontent.com/280700/148732476-406c13c6-285d-494a-b83a-6ccecbf942a8.png)

**Comment by Soni96pl** [comment]
Same with 13.0.2 it's likely one of the dependencies

**Comment by zbynek** [comment]
Before you report an issue you may want to check it's already reported or addressed by a PR. See #781, #782, #783, #784, #785, #786

**Comment by JohyC** [comment]
Oh! thanks guys! I`m reading for #294 , and looking for how to fix it. I will close this issues. @Soni96pl @zbynek

**Comment by scottstanfield** [comment]
Thanks for the heads-up. Just saw the article https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/
