### ISSUE TITLE
next js dynamic page

### ISSUE THREAD

**Issue by benamm** [http-party/http-server#819]
how serve next js dynamic pages like that 
![image](https://user-images.githubusercontent.com/40948849/173878058-de3f7bab-203a-47cc-b9b0-de46538b389e.png)

currently I see 
![image](https://user-images.githubusercontent.com/40948849/173878179-a1b1e0dd-26a5-420d-b1ee-f9ce48723dea.png)

**Comment by sepehrsamavati** [comment]
This module is a static http server which is good for serving static files (a simple file server).
It's better to make the server yourself so you have full control over it. (e.g. `express` framework)
