### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by babadoctor** [http-party/http-server#855]
#### Environment Versions

1. OS Type
**Linux diode 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux**
(debian bullseye)
1. Node version: `$ node --version`
v12.22.12

1. http-server version: `$ http-server --version`
v14.1.1

#### Steps to reproduce

sudo http-server -p 80 --log-ip

#### Expected result

runs like normal

#### Actual result

for some unknown reason http-server quits with error, this was caused when a vulnerability scanner did something to it and it crashed.
![Screen_Shot_2023-04-10_at_5 42 34_PM](https://user-images.githubusercontent.com/8715318/231306046-5ac20a0d-0b49-4fbf-9b58-42d8acbd4824.png)

...

**Comment by zbynek** [comment]
Do you have `index.html` in your root folder? What is the last modification date of it? I can reproduce the error if I manually set the modification date of `index.html` to some nonsense (e.g. using `touch -d '1937-01-31 8:46:26' index.html`
` on Linux).

**Comment by babadoctor** [comment]
> Do you have `index.html` in your root folder? What is the last modification date of it? I can reproduce the error if I manually set the modification date of `index.html` to some nonsense (e.g. using `touch -d '1937-01-31 8:46:26' index.html` on Linux).

I am running a hugo static webpage and in the root directory of the webpage I am running http-server, and it seems to work.

The index.html file is in a folder within the root directory called "public".
<img width="518" alt="Screen Shot 2023-04-11 at 5 08 09 PM" src="https://user-images.githubusercontent.com/8715318/231314521-44640419-a4b4-4093-bbfe-ddba2f3b4dd5.png">
