### ISSUE TITLE
OWASP vulnerability in dependency tree 

### ISSUE THREAD

**Issue by gauravghumakkad** [http-party/http-server#860]
There are various published vulnerabilities in one of the dependency of http-server 
"http-server": "^14.1.0" => **"opener": "^1.5.1"**

Requesting to please check on this .

**Comment by KernelDeimos** [comment]
Hello, I'd like to address this but I need more information to address it properly.

- Snyk seems to think everything is fine: https://snyk.io/advisor/npm-package/opener
- Opener has [one small change](https://github.com/domenic/opener/commit/77fd77908e34f780b42e81d16dd955083dd9adf3) in 1.5.2 that looks like it could be related to security

Given that the extent of the change in 1.5.2 is small I have no problem updating the package. However I'm unable to find any source mentioning a vulnerability and whether 1.5.2 addresses it.

**Comment by KernelDeimos** [comment]
I found the comment (https://github.com/nrwl/nx/issues/22206#issuecomment-2150286778) that explains what's going on. That vulnerability report is not at all related to `opener` module that http-server is using. Please be very careful about producing/propagating inaccurate vulnerability reports as it can cause a lot of grief for maintainers (both of the respective projects and outside of them).
