### ISSUE TITLE
{"message":"You are not authorized"} in GitHub Codespace

### ISSUE THREAD

**Issue by davetapley** [http-party/http-server#864]
#### Environment Versions

1. OS Type
1. Node version: `v18.17.1`
1. http-server version: `v14.1.1`

#### Steps to reproduce

1. Start a [GitHub Codespace](https://github.com/features/codespaces)
2. `npx http-server`
3. Codespace will auto-forward port 8080

#### Expected result

Navigate to http://localhost:8080/ in browser and see files

#### Actual result

Navigate to http://localhost:8080/ and see:
```
{"message":"You are not authorized"}
```

...

#### Other information

I'm not 100% sure if this is `http-server` or Codespace, but I figured I'd open in case others see / can reproduce.

If I `curl localhost:8080` in the Codespace I can see the listing just fine, and https://ngrok.com/ works too.

See also: https://github.com/orgs/community/discussions/64558

**Comment by zbynek** [comment]
For me it works with empty codespace (which by default has Node 20 -- not sure if that could be different to Node 18).

> Navigate to http://localhost:8080/ in browser and see files

Note that the URL in browser address bar needs to be something like https://foo-bar-baz-8080.app.github.dev/ -- if you actually try to open localhost in your browser it won't work.

Also: when you're running http-server in terminal, you should see a log of all the URLs that were served -- does it produce any output when you try to open the codespace URL in a browser?
