### ISSUE TITLE
Fix `localhost.test.js`

### ISSUE THREAD

**Issue by KernelDeimos** [http-party/http-server#895]
The test `localhost.test.js` is failing with a `404` response when the host address is `::1` rather than `localhost` or `127.0.0.1`. #830 adds support for `::` as the permissive listening address so we should fix this to be consistent.

**Comment by n00nchi** [comment]
Can I pick this up?

**Comment by n00nchi** [comment]
PR: https://github.com/http-party/http-server/pull/896

Review when you get the chance. Thank you!
