### ISSUE TITLE
Node.js CI workflow is broken

### ISSUE THREAD

**Issue by ixth** [http-party/http-server#904]
It seems like bumping `tap` to `tap@^21.0.1` has broken CI workflow:
- it requires Node >=20
- it no longer support `spec` reporter
- it returns exit code 1 if coverage is not 100%

#### Environment Versions

1. Any OS
1. All available Node versions
1. http-server version: latest

#### Steps to reproduce

1. Make a PR and see Node.js CI workflow in `Actions` tab

#### Expected result

1. Green jobs
2. Green build badge

#### Actual result

Here's workflow ran against current master branch:
<img width="1040" alt="workflow ran against current master branch" src="https://github.com/user-attachments/assets/269d0958-be7e-43f7-a972-42ff841a37f8">

**Comment by KernelDeimos** [comment]
This seems to be, as far as I can tell, because I updated `tap` and it no longer runs in node < 16.

**Comment by ixth** [comment]
@KernelDeimos Is it okay that I bumped engine in package.json, though? Project's policy on supported node versions is unclear and this change makes it not backward-compatible. Should major version be updated in the next release, then?

**Comment by KernelDeimos** [comment]
Good point; I wish there was a `node_dev` version - some place to put a version number that's for development only (like tests). I think the commit immediately before this was merged can be `14.2.0` and anything after will be in `15.x.x`
