### ISSUE TITLE
pls can you add -w watch option to this amazing module

### ISSUE THREAD

**Issue by programming-kid** [http-party/http-server#95]
it would be really nice to have watch and reload option for `http-server` , i use this package all the time and what bugs me is i have to refresh broiwer after making changes all the time.

I wish this had -w watch option which would watch current directory and reload after changes are detected , i know this can be done with other plugins but i wish http-server server had this funtionality.

Thanks

**Comment by tleite** [comment]
LOL dang, you just told the guy to go refresh himself
